
/* -----------------------------------------------------------------------------
Software Copyright License for The Fraunhofer FDK Extended High Efficiency AAC
Encoder Software for Android

© Copyright 1995 - 2025 Fraunhofer-Gesellschaft zur Förderung der angewandten
Forschung e.V. and Contributors
All rights reserved.

1.    INTRODUCTION

The Fraunhofer FDK Extended High Efficiency AAC Encoder Software for Android
("FDK Extended High Efficiency AAC Encoder") is software that implements the
encoding of digital audio according to the MPEG-D Unified Speech and Audio
Coding (USAC) standard and MPEG-D Dynamic Range Control (DRC) standard. This FDK
Extended High Efficiency AAC Encoder Software is intended to be used on a wide
variety of Android devices. It is technically not suited to encode content for
digital radio broadcasting services, including DRM and similar standards.

Patent licenses for necessary patent claims for the FDK Extended High Efficiency
AAC Encoder Software (including those of Fraunhofer), for the use in commercial
products and services, may be obtained from the respective patent owners
individually and/or from Via Licensing Alliance (www.via-la.com).

Fraunhofer supports the development of Extended High Efficiency AAC products and
services by offering additional software, documentation, and technical advice.
In addition, it operates the xHE-AAC Trademark Program to ease interoperability
testing of end products. Please visit http://www.xhe-aac.com for more
information.

2.    COPYRIGHT LICENSE

Redistribution and use in source and binary forms, with or without modification,
are permitted without payment of copyright license fees, provided that you
satisfy the following conditions:

You must retain the complete text of this software license in redistributions of
the FDK Extended High Efficiency AAC Encoder Software or your modifications
thereto in source code form.

You must retain the complete text of this software license in the documentation
and/or other materials provided with redistributions of the FDK Extended High
Efficiency AAC Encoder Software or your modifications thereto in binary form.
You must make available free of charge copies of the complete source code of the
FDK Extended High Efficiency AAC Encoder Software and your modifications thereto
to recipients of copies in binary form.

The name of Fraunhofer may not be used to endorse or promote products derived
from this software without prior written permission.

You may not charge copyright license fees for anyone to use, copy or distribute
the FDK Extended High Efficiency AAC Encoder Software or your modifications
thereto.

Your modified versions of the FDK Extended High Efficiency AAC Encoder Software
must carry prominent notices stating that you changed the software and the date
of any change. For modified versions of the FDK Extended High Efficiency AAC
Encoder Software, the term "Fraunhofer FDK Extended High Efficiency AAC Encoder
Software for Android" must be replaced by the term "Third-Party Modified Version
of the Fraunhofer FDK Extended High Efficiency AAC Encoder Software for
Android."

3.    NO PATENT LICENSE

NO EXPRESS OR IMPLIED LICENSES TO ANY PATENT CLAIMS, including without
limitation the patents of Fraunhofer, ARE GRANTED BY THIS SOFTWARE LICENSE.
Fraunhofer provides no warranty for patent non-infringement with respect to this
software. You may use this FDK Extended High Efficiency AAC Encoder Software or
modifications thereto only for purposes that are authorized by appropriate
patent licenses.

4.    DISCLAIMER

This FDK Extended High Efficiency AAC Encoder Software is provided by Fraunhofer
on behalf of the copyright holders and contributors "AS IS" and WITHOUT ANY
EXPRESS OR IMPLIED WARRANTIES, including but not limited to the implied
warranties of merchantability and fitness for a particular purpose. IN NO EVENT
SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE for any direct, indirect,
incidental, special, exemplary, or consequential damages, including but not
limited to procurement of substitute goods or services; loss of use, data, or
profits, or business interruption, however caused and on any theory of
liability, whether in contract, strict liability, or tort (including
negligence), arising in any way out of the use of this software, even if advised
of the possibility of such damage.

5.    CONTACT INFORMATION

Fraunhofer Institute for Integrated Circuits IIS
Attention: Division Audio and Media Technologies - FDK Extended High Efficiency
AAC Encoder
Am Wolfsmantel 33
91058 Erlangen, Germany

www.iis.fraunhofer.de/amm
amm-info@iis.fraunhofer.de
----------------------------------------------------------------------------- */

#ifndef IISENCODERCONFIG_H
#define IISENCODERCONFIG_H

#include "iisutillib.h"
#include "iisParamList.h"

#define ENCODERCONFIG_WARNING_FIRST 0x00000010
#define ENCODERCONFIG_ERROR_FIRST 0x00010000

typedef enum {
  ENCODERCONFIG_NO_ERROR = 0,
  ENCODERCONFIG_WARNING_RESERVED = ENCODERCONFIG_WARNING_FIRST,
  ENCODERCONFIG_ERROR_MEMORY = ENCODERCONFIG_ERROR_FIRST,
  ENCODERCONFIG_ERROR_INVALID_HANDLE,
  ENCODERCONFIG_ERROR_INVALID_PARAM,

  ENCODERCONFIG_ERROR_NO_CONFIG_IN_CONFIGTABLE,

  ENCODERCONFIG_ERROR_INVALID_CHANNELCONFIG,
  ENCODERCONFIG_ERROR_INVALID_BITRATE,
  ENCODERCONFIG_ERROR_INVALID_BITRATEMODE,
  ENCODERCONFIG_ERROR_INVALID_INPUT_SR,
  ENCODERCONFIG_ERROR_INVALID_OUTPUT_SR,
  ENCODERCONFIG_ERROR_INVALID_SBR_RATIO,
  ENCODERCONFIG_ERROR_INVALID_GRANULELENGTH,
  ENCODERCONFIG_ERROR_INVALID_FRAMESAMPLES,
  ENCODERCONFIG_ERROR_INVALID_CONFIGSET,
  ENCODERCONFIG_ERROR_INVALID_PRESET,
  ENCODERCONFIG_ERROR_INVALID_TRANSPORTFORMAT,
  ENCODERCONFIG_ERROR_INVALID_AOT,
  ENCODERCONFIG_ERROR_INVALID_RAP_PROPERTY,
  ENCODERCONFIG_ERROR_INVALID_RAP_OCCURRENCE,
  ENCODERCONFIG_ERROR_INVALID_USAC_IFI,
  ENCODERCONFIG_ERROR_INVALID_USAC_IFI_DRM,
  ENCODERCONFIG_ERROR_INVALID_RAP_INTERVAL,
  ENCODERCONFIG_ERROR_INVALID_SKIPDELAY,
  ENCODERCONFIG_ERROR_INVALID_LOUDNESSLEVEL,
  ENCODERCONFIG_ERROR_INVALID_ALBUM_LOUDNESSLEVEL,
  ENCODERCONFIG_ERROR_INVALID_ANCHOR_LOUDNESSLEVEL,
  ENCODERCONFIG_ERROR_NO_LOUDNESS_PROVIDED,
  ENCODERCONFIG_ERROR_INVALID_QUIET_LOUDNESS_THRESHOLD,
  ENCODERCONFIG_ERROR_MISSING_QUIET_LOUDNESS_THRESHOLD,
  ENCODERCONFIG_ERROR_INVALID_DRCMODE,

  ENCODERCONFIG_ERROR_INVALID_COMB_TSD_UNIFIEDSTEREO,
  ENCODERCONFIG_ERROR_INVALID_COMB_BITRATE_CORESAMPLERATE,
  ENCODERCONFIG_ERROR_INVALID_COMB_BITRATE_DRM,
  ENCODERCONFIG_ERROR_INVALID_COMB_SAMPLERATE_NOSBR_DRM30,
  ENCODERCONFIG_ERROR_INVALID_COMB_DRC_LOUDNESS,
  ENCODERCONFIG_ERROR_INVALID_COMB_DRC_MODE_LRACONTROL_DATA,
  ENCODERCONFIG_ERROR_INVALID_COMB_DRC_MODE_TARGET_LRA,
  ENCODERCONFIG_ERROR_INVALID_COMB_LOUDNESSLEVEL_DISABLELOUDNESS,
  ENCODERCONFIG_ERROR_INVALID_COMB_LOUDNESSLEVEL_ALBUMLOUDNESS,
  ENCODERCONFIG_ERROR_INVALID_COMB_LOUDNESSLEVEL_ANCHORLOUDNESS,
  ENCODERCONFIG_ERROR_INVALID_COMB_LOUDNESSLEVEL_QUIETLOUDNESSTHRESHOLD,
  ENCODERCONFIG_ERROR_INVALID_COMB_ANCHORLOUDNESSLEVEL_QUIETLOUDNESSTHRESHOLD,
  ENCODERCONFIG_ERROR_INVALID_COMB_AOT_LOUDNESSLEVEL,
  ENCODERCONFIG_ERROR_INVALID_COMB_PROGREFLEVEL_MPEGDDRC,
  ENCODERCONFIG_ERROR_INVALID_COMB_PROGREFLEVEL_AOT,
  ENCODERCONFIG_ERROR_INVALID_COMB_PROGREFLEVEL_QUIETLOUDNESSTHRESHOLD,
  ENCODERCONFIG_ERROR_INVALID_COMB_MPEG4DRC_DISABLELOUDNESSMEASUREMENT,
  ENCODERCONFIG_ERROR_INVALID_COMB_INSAMPLERATE_AOT_OUTSAMPLERATE,
  ENCODERCONFIG_ERROR_INVALID_COMB_CHANNELCONFIG_LIVELOUDNESS,
  ENCODERCONFIG_ERROR_INVALID_COMB_LOUDNESSLEVEL_LIVELOUDNESSLEVEL,
  ENCODERCONFIG_ERROR_INVALID_COMB_SAMPLEPEAK_LIVESAMPLEPEAK,
  ENCODERCONFIG_ERROR_INVALID_COMB_AOT_LIVELOUDNESSLEVEL,
  ENCODERCONFIG_ERROR_INVALID_COMB_LIVESAMPLEPEAK_NOLIVELOUDNESSLEVEL,
  ENCODERCONFIG_ERROR_INVALID_COMB_SAMPLEPEAK_LIVELOUDNESSLEVEL,
  ENCODERCONFIG_ERROR_INVALID_COMB_LIVELOUDNESSLEVEL_DISABLELOUDNESS,
  ENCODERCONFIG_ERROR_INVALID_COMB_LIVELOUDNESSLEVEL_ALBUMLOUDNESS,
  ENCODERCONFIG_ERROR_INVALID_COMB_LIVELOUDNESSLEVEL_ANCHORLOUDNESS,
  ENCODERCONFIG_ERROR_INVALID_COMB_LIVELOUDNESSLEVEL_QUIETLOUDNESSTHRESHOLD,
  ENCODERCONFIG_ERROR_INVALID_COMB_NO_LIVELOUDNESSLEVEL_LIVEMODE,
  ENCODERCONFIG_ERROR_INVALID_COMB_NO_LIVELOUDNESSLEVEL_LIVERELMAXGAIN,
  ENCODERCONFIG_ERROR_INVALID_COMB_DRC_MODE_LIVE_LRA_CONTROL,
  ENCODERCONFIG_ERROR_INVALID_COMB_FLUSHINGMODE_DRC,
  ENCODERCONFIG_ERROR_INVALID_COMB_RAP_PROPERTY_RAP_OCCURRENCE,
  ENCODERCONFIG_ERROR_INVALID_COMB_RAP_TRANSPORTFORMAT,
  ENCODERCONFIG_ERROR_INVALID_COMB_RAP_OCCURRENCE_RAP_INTERVAL,
  ENCODERCONFIG_ERROR_INVALID_COMB_RAP_INTERVAL_RAP_MIN_INTERVAL,
  ENCODERCONFIG_ERROR_INVALID_COMB_RAP_ON_DEMAND_ADVANCED_MODE,
  ENCODERCONFIG_ERROR_INVALID_COMB_DRC_DRM,
  ENCODERCONFIG_ERROR_INVALID_COMB_HBE_STEREOCONFIGIDX,
  ENCODERCONFIG_ERROR_INVALID_COMB_MPEG2AAC_AOT,
  ENCODERCONFIG_ERROR_INVALID_COMB_NOSTARTSTOP_AOT,
  ENCODERCONFIG_ERROR_INVALID_COMB_AOT_MPEG4DRC,
  ENCODERCONFIG_ERROR_INVALID_COMB_MPEG4DRC_LOUDNESS,
  ENCODERCONFIG_ERROR_INVALID_COMB_MDMODE_PROGREFLVL,
  ENCODERCONFIG_ERROR_INVALID_COMB_AOT_MD,
  ENCODERCONFIG_ERROR_INVALID_COMB_MD_NONE_DRC,
  ENCODERCONFIG_ERROR_INVALID_COMB_MD_MODE_SURROUND,
  ENCODERCONFIG_ERROR_INVALID_COMB_MD_CHANNELCONFIG_SURROUND,
  ENCODERCONFIG_ERROR_INVALID_COMB_AOT_MPEG_D_DRC,
  ENCODERCONFIG_ERROR_INVALID_COMB_AOT_LRAC,
  ENCODERCONFIG_ERROR_INVALID_COMB_DRC_MPEG4DRC,
  ENCODERCONFIG_ERROR_INVALID_COMB_VBR_MPEG4DRC,
  ENCODERCONFIG_ERROR_INVALID_COMB_BITRATE_BITRATEMODE,
  ENCODERCONFIG_ERROR_INVALID_COMB_AOT_42_OPERATINGMODE_PRIMING,
  ENCODERCONFIG_ERROR_INVALID_COMB_OPERATINGMODE_PRIMING,
  ENCODERCONFIG_ERROR_INVALID_COMB_AOT_LOUDNESS_DRC,
  ENCODERCONFIG_ERROR_INVALID_COMB_AOT_BITRATEMODE_CHANNELCONFIG,
  ENCODERCONFIG_ERROR_INVALID_COMB_RAP_PROPERTY_PRIMING,
  ENCODERCONFIG_ERROR_INVALID_COMB_PRESET_AOT,
  ENCODERCONFIG_ERROR_INVALID_COMB_PRESET_AOT_CHANNELCONFIG,
  ENCODERCONFIG_ERROR_INVALID_COMB_AOT42_RAP_PROPERTY_PRIMING,
  ENCODERCONFIG_ERROR_INVALID_COMB_SHORTEST_RAP_INTVL_APR_BITRESMODE,
  ENCODERCONFIG_ERROR_INVALID_COMB_SHORTEST_RAP_INTVL_RAP_OCCURRENCE,
  ENCODERCONFIG_ERROR_INVALID_COMB_TIMESIGNAL_PREPROC,
  ENCODERCONFIG_ERROR_INVALID_COMB_TIMESIGNAL_PREPROC_AOT,
  ENCODERCONFIG_ERROR_INVALID_COMB_AOT_SBRSIGNALING,
  ENCODERCONFIG_ERROR_INVALID_COMB_MD_MPEG_DRC_HEAVY,
  ENCODERCONFIG_ERROR_INVALID_COMB_MD_MODE_DRC_PRES_MODE,
  ENCODERCONFIG_ERROR_INVALID_COMB_MD_CHANNELCONFIG_DOWNMIX,
  ENCODERCONFIG_ERROR_INVALID_COMB_MD_MODE_CHANNELCONFIG_DOWNMIX,
  ENCODERCONFIG_ERROR_INVALID_COMB_MD_DRC_PRES_TARGETREFLVL,

  ENCODERCONFIG_ERROR_REQUIRED_STREAMID_FOR_SWITCHABLE_AND_AOT42,
  ENCODERCONFIG_ERROR_REQUIRED_TARGETLOUDNESS_FOR_MPEG4DRCLIGHT,
  ENCODERCONFIG_ERROR_REQUIRED_TARGETLOUDNESS_FOR_MPEG4DRCHEAVY,
  ENCODERCONFIG_ERROR_REQUIRED_MPEG4PROGREFLEVEL_FOR_MPEG4DRC,
  ENCODERCONFIG_ERROR_REQUIRED_MPEG4DRC_FOR_MPEG4METADATA,

  ENCODERCONFIG_ERROR_FORBIDDEN_MPEG4DRCHEAVY_NOT_MPEG4DRCLIGHT,
  ENCODERCONFIG_ERROR_FORBIDDEN_STREAMID_FOR_NOT_AOT42,
  ENCODERCONFIG_ERROR_FORBIDDEN_DRM_WITHOUT_DEVELOPER,
  ENCODERCONFIG_ERROR_FORBIDDEN_RAP_PROPERTY_CONFIGSET,
  ENCODERCONFIG_ERROR_UNKNOWN_ERROR_IN_SUBMODULE
} ENCODERCONFIG_RETURN_CODE;

typedef enum {
  ENCCONFIG_INIT = 0,
  ENCCONFIG_UPDATE = 1
} ENCCONFIG_SET;

typedef struct encconfig_instance_struct {
  char infoModuleVersion[32];
} ENCCONFIG_INSTANCE, *ENCCONFIG_INSTANCE_HANDLE;

ENCODERCONFIG_RETURN_CODE iisEncoderConfigNew(
    ENCCONFIG_INSTANCE_HANDLE *phInstance);

ENCODERCONFIG_RETURN_CODE iisEncoderConfigUpdate(
    ENCCONFIG_INSTANCE_HANDLE hInstance,
    PARAMLIST_INSTANCE_HANDLE hUserParamList,
    PARAMLIST_INSTANCE_HANDLE hCodecParamList);

ENCODERCONFIG_RETURN_CODE iisEncoderConfigDelete(
    ENCCONFIG_INSTANCE_HANDLE hInstance);

#endif
