
/* -----------------------------------------------------------------------------
Software Copyright License for The Fraunhofer FDK Extended High Efficiency AAC
Encoder Software for Android

© Copyright 1995 - 2025 Fraunhofer-Gesellschaft zur Förderung der angewandten
Forschung e.V. and Contributors
All rights reserved.

1.    INTRODUCTION

The Fraunhofer FDK Extended High Efficiency AAC Encoder Software for Android
("FDK Extended High Efficiency AAC Encoder") is software that implements the
encoding of digital audio according to the MPEG-D Unified Speech and Audio
Coding (USAC) standard and MPEG-D Dynamic Range Control (DRC) standard. This FDK
Extended High Efficiency AAC Encoder Software is intended to be used on a wide
variety of Android devices. It is technically not suited to encode content for
digital radio broadcasting services, including DRM and similar standards.

Patent licenses for necessary patent claims for the FDK Extended High Efficiency
AAC Encoder Software (including those of Fraunhofer), for the use in commercial
products and services, may be obtained from the respective patent owners
individually and/or from Via Licensing Alliance (www.via-la.com).

Fraunhofer supports the development of Extended High Efficiency AAC products and
services by offering additional software, documentation, and technical advice.
In addition, it operates the xHE-AAC Trademark Program to ease interoperability
testing of end products. Please visit http://www.xhe-aac.com for more
information.

2.    COPYRIGHT LICENSE

Redistribution and use in source and binary forms, with or without modification,
are permitted without payment of copyright license fees, provided that you
satisfy the following conditions:

You must retain the complete text of this software license in redistributions of
the FDK Extended High Efficiency AAC Encoder Software or your modifications
thereto in source code form.

You must retain the complete text of this software license in the documentation
and/or other materials provided with redistributions of the FDK Extended High
Efficiency AAC Encoder Software or your modifications thereto in binary form.
You must make available free of charge copies of the complete source code of the
FDK Extended High Efficiency AAC Encoder Software and your modifications thereto
to recipients of copies in binary form.

The name of Fraunhofer may not be used to endorse or promote products derived
from this software without prior written permission.

You may not charge copyright license fees for anyone to use, copy or distribute
the FDK Extended High Efficiency AAC Encoder Software or your modifications
thereto.

Your modified versions of the FDK Extended High Efficiency AAC Encoder Software
must carry prominent notices stating that you changed the software and the date
of any change. For modified versions of the FDK Extended High Efficiency AAC
Encoder Software, the term "Fraunhofer FDK Extended High Efficiency AAC Encoder
Software for Android" must be replaced by the term "Third-Party Modified Version
of the Fraunhofer FDK Extended High Efficiency AAC Encoder Software for
Android."

3.    NO PATENT LICENSE

NO EXPRESS OR IMPLIED LICENSES TO ANY PATENT CLAIMS, including without
limitation the patents of Fraunhofer, ARE GRANTED BY THIS SOFTWARE LICENSE.
Fraunhofer provides no warranty for patent non-infringement with respect to this
software. You may use this FDK Extended High Efficiency AAC Encoder Software or
modifications thereto only for purposes that are authorized by appropriate
patent licenses.

4.    DISCLAIMER

This FDK Extended High Efficiency AAC Encoder Software is provided by Fraunhofer
on behalf of the copyright holders and contributors "AS IS" and WITHOUT ANY
EXPRESS OR IMPLIED WARRANTIES, including but not limited to the implied
warranties of merchantability and fitness for a particular purpose. IN NO EVENT
SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE for any direct, indirect,
incidental, special, exemplary, or consequential damages, including but not
limited to procurement of substitute goods or services; loss of use, data, or
profits, or business interruption, however caused and on any theory of
liability, whether in contract, strict liability, or tort (including
negligence), arising in any way out of the use of this software, even if advised
of the possibility of such damage.

5.    CONTACT INFORMATION

Fraunhofer Institute for Integrated Circuits IIS
Attention: Division Audio and Media Technologies - FDK Extended High Efficiency
AAC Encoder
Am Wolfsmantel 33
91058 Erlangen, Germany

www.iis.fraunhofer.de/amm
amm-info@iis.fraunhofer.de
----------------------------------------------------------------------------- */

#include "iisEncoderConfigCTable.h"

#define AVOID_COMPILER_WARNING(expr) \
  do {                               \
    (void)(expr);                    \
  } while (0);

#include "rel_coremode.h"
#include "rel_outsamplerate.h"
#include "rel_quality.h"
#include "rel_sbrsignaling.h"
#include "rel_sbrratio.h"
#include "rel_stereoconfigidx.h"
#include "rel_hbe.h"
#include "rel_sbrpvc.h"
#include "rel_tsd.h"

#define CFG_MAIN_AOT_42_DASH_OSS 0x91051709

typedef struct main_aot_42_dash_oss_default_struct {
  PARAMLIST_AOT aot;
  PARAMLIST_BITRATE bitratemin;
  PARAMLIST_BITRATE bitratemax;
  PARAMLIST_BITRATE bitrate;
  PARAMLIST_BITRATEMODE bitratemode;
  PARAMLIST_CHANNELCONFIG channelconfig;
  PARAMLIST_TRANSPORTFORMAT transportformat;
  PARAMLIST_CONFIGSET configset;
  PARAMLIST_KEYCOREMODE keycoremode;
  PARAMLIST_KEYOUTSAMPLERATE keyoutsamplerate;
  PARAMLIST_KEYQUALITY keyquality;
  PARAMLIST_KEYSBRSIGNALING keysbrsignaling;
  PARAMLIST_KEYSBRRATIO keysbrratio;
  PARAMLIST_KEYSTEREOCONFIGIDX keystereoconfigidx;
  PARAMLIST_KEYHBE keyhbe;
  PARAMLIST_NOISEFILLING noisefilling;
  PARAMLIST_KEYSBRPVC keysbrpvc;
  PARAMLIST_SBRRAISEDXOVERFREQ sbrraisedxoverfreq;
  PARAMLIST_ACELPMODEINDEX acelpmodeindex;
  PARAMLIST_KEYTSD keytsd;

} MAIN_AOT_42_DASH_OSS_DEFAULT;

static MAIN_AOT_42_DASH_OSS_DEFAULT const main_aot_42_dash_oss_default[] = {

    {PARAMLIST_AOT_42, 88000, 111999, 96000, PARAMLIST_BITRATEMODE_CBR, PARAMLIST_CHANNELCONFIG_STEREO, PARAMLIST_TRANSPORTFORMAT_RAW, PARAMLIST_CONFIGSET_DASH, KEY_COREMODE_FD, KEY_OUTSR_LST_44100_48000_D44100_D48000, KEY_QUALITY_HIGH, KEY_SBRSIGNALING_EXPL_HIER, KEY_SBRRATIO_NONE, KEY_STEREOCONFIGIDX_ALL_0, KEY_HBE_OFF, PARAMLIST_NOISEFILLING_OFF, KEY_SBRPVC_OFF, 0, 7, KEY_TSD_OFF},
    {PARAMLIST_AOT_42, 88000, 111999, 96000, PARAMLIST_BITRATEMODE_VBR3, PARAMLIST_CHANNELCONFIG_STEREO, PARAMLIST_TRANSPORTFORMAT_RAW, PARAMLIST_CONFIGSET_DASH, KEY_COREMODE_FD, KEY_OUTSR_LST_44100_48000_D44100_D48000, KEY_QUALITY_HIGH, KEY_SBRSIGNALING_EXPL_HIER, KEY_SBRRATIO_NONE, KEY_STEREOCONFIGIDX_ALL_0, KEY_HBE_OFF, PARAMLIST_NOISEFILLING_OFF, KEY_SBRPVC_OFF, 0, 7, KEY_TSD_OFF},

};

typedef struct main_aot_42_dash_oss_struct {
  PARAMLIST_AOT aot;
  PARAMLIST_BITRATE bitratemin;
  PARAMLIST_BITRATE bitratemax;
  PARAMLIST_BITRATE bitrate;
  PARAMLIST_BITRATEMODE bitratemode;
  PARAMLIST_CHANNELCONFIG channelconfig;
  PARAMLIST_TRANSPORTFORMAT transportformat;
  PARAMLIST_CONFIGSET configset;
  PARAMLIST_KEYCOREMODE keycoremode;
  PARAMLIST_KEYOUTSAMPLERATE keyoutsamplerate;
  PARAMLIST_KEYQUALITY keyquality;
  PARAMLIST_KEYSBRSIGNALING keysbrsignaling;
  PARAMLIST_KEYSBRRATIO keysbrratio;
  PARAMLIST_KEYSTEREOCONFIGIDX keystereoconfigidx;
  PARAMLIST_KEYHBE keyhbe;
  PARAMLIST_NOISEFILLING noisefilling;
  PARAMLIST_KEYSBRPVC keysbrpvc;
  PARAMLIST_SBRRAISEDXOVERFREQ sbrraisedxoverfreq;
  PARAMLIST_ACELPMODEINDEX acelpmodeindex;
  PARAMLIST_KEYTSD keytsd;

} MAIN_AOT_42_DASH_OSS;

static MAIN_AOT_42_DASH_OSS const main_aot_42_dash_oss[] = {

    {PARAMLIST_AOT_42, 11000, 12999, 12000, PARAMLIST_BITRATEMODE_CBR, PARAMLIST_CHANNELCONFIG_MONO, PARAMLIST_TRANSPORTFORMAT_RAW, PARAMLIST_CONFIGSET_DASH, KEY_COREMODE_ALL_LPD, KEY_OUTSR_LST_44100_48000_D44100_D48000, KEY_QUALITY_HIGH, KEY_SBRSIGNALING_EXPL_HIER, KEY_SBRRATIO_4_1, KEY_STEREOCONFIGIDX_NONE, KEY_HBE_OFF, PARAMLIST_NOISEFILLING_ON, KEY_SBRPVC_OFF, 1, 3, KEY_TSD_OFF},
    {PARAMLIST_AOT_42, 11000, 12999, 12000, PARAMLIST_BITRATEMODE_CBR, PARAMLIST_CHANNELCONFIG_MONO, PARAMLIST_TRANSPORTFORMAT_LATMLOAS, PARAMLIST_CONFIGSET_DASH, KEY_COREMODE_ALL_LPD, KEY_OUTSR_LST_44100_48000_D44100_D48000, KEY_QUALITY_HIGH, KEY_SBRSIGNALING_EXPL_HIER, KEY_SBRRATIO_4_1, KEY_STEREOCONFIGIDX_NONE, KEY_HBE_OFF, PARAMLIST_NOISEFILLING_ON, KEY_SBRPVC_OFF, 1, 3, KEY_TSD_OFF},
    {PARAMLIST_AOT_42, 13000, 14999, 14000, PARAMLIST_BITRATEMODE_CBR, PARAMLIST_CHANNELCONFIG_MONO, PARAMLIST_TRANSPORTFORMAT_RAW, PARAMLIST_CONFIGSET_DASH, KEY_COREMODE_ALL_SWITCHED, KEY_OUTSR_LST_44100_48000_D44100_D48000, KEY_QUALITY_HIGH, KEY_SBRSIGNALING_EXPL_HIER, KEY_SBRRATIO_4_1, KEY_STEREOCONFIGIDX_NONE, KEY_HBE_OFF, PARAMLIST_NOISEFILLING_ON, KEY_SBRPVC_OFF, 0, 3, KEY_TSD_OFF},
    {PARAMLIST_AOT_42, 13000, 14999, 14000, PARAMLIST_BITRATEMODE_CBR, PARAMLIST_CHANNELCONFIG_MONO, PARAMLIST_TRANSPORTFORMAT_LATMLOAS, PARAMLIST_CONFIGSET_DASH, KEY_COREMODE_ALL_SWITCHED, KEY_OUTSR_LST_44100_48000_D44100_D48000, KEY_QUALITY_HIGH, KEY_SBRSIGNALING_EXPL_HIER, KEY_SBRRATIO_4_1, KEY_STEREOCONFIGIDX_NONE, KEY_HBE_OFF, PARAMLIST_NOISEFILLING_ON, KEY_SBRPVC_OFF, 0, 3, KEY_TSD_OFF},
    {PARAMLIST_AOT_42, 15000, 17999, 16000, PARAMLIST_BITRATEMODE_CBR, PARAMLIST_CHANNELCONFIG_MONO, PARAMLIST_TRANSPORTFORMAT_RAW, PARAMLIST_CONFIGSET_DASH, KEY_COREMODE_ALL_SWITCHED, KEY_OUTSR_LST_44100_48000_D44100_D48000, KEY_QUALITY_HIGH, KEY_SBRSIGNALING_EXPL_HIER, KEY_SBRRATIO_4_1, KEY_STEREOCONFIGIDX_NONE, KEY_HBE_OFF, PARAMLIST_NOISEFILLING_ON, KEY_SBRPVC_OFF, 0, 4, KEY_TSD_OFF},
    {PARAMLIST_AOT_42, 15000, 17999, 16000, PARAMLIST_BITRATEMODE_CBR, PARAMLIST_CHANNELCONFIG_MONO, PARAMLIST_TRANSPORTFORMAT_LATMLOAS, PARAMLIST_CONFIGSET_DASH, KEY_COREMODE_ALL_SWITCHED, KEY_OUTSR_LST_44100_48000_D44100_D48000, KEY_QUALITY_HIGH, KEY_SBRSIGNALING_EXPL_HIER, KEY_SBRRATIO_4_1, KEY_STEREOCONFIGIDX_NONE, KEY_HBE_OFF, PARAMLIST_NOISEFILLING_ON, KEY_SBRPVC_OFF, 0, 4, KEY_TSD_OFF},
    {PARAMLIST_AOT_42, 15000, 17999, 16000, PARAMLIST_BITRATEMODE_CBR, PARAMLIST_CHANNELCONFIG_STEREO, PARAMLIST_TRANSPORTFORMAT_RAW, PARAMLIST_CONFIGSET_DASH, KEY_COREMODE_ALL_SWITCHED, KEY_OUTSR_LST_44100_48000_D44100_D48000, KEY_QUALITY_HIGH, KEY_SBRSIGNALING_EXPL_HIER, KEY_SBRRATIO_4_1, KEY_STEREOCONFIGIDX_ALL_1, KEY_HBE_OFF, PARAMLIST_NOISEFILLING_ON, KEY_SBRPVC_OFF, 0, 4, KEY_TSD_ON},
    {PARAMLIST_AOT_42, 15000, 17999, 16000, PARAMLIST_BITRATEMODE_CBR, PARAMLIST_CHANNELCONFIG_STEREO, PARAMLIST_TRANSPORTFORMAT_LATMLOAS, PARAMLIST_CONFIGSET_DASH, KEY_COREMODE_ALL_SWITCHED, KEY_OUTSR_LST_44100_48000_D44100_D48000, KEY_QUALITY_HIGH, KEY_SBRSIGNALING_EXPL_HIER, KEY_SBRRATIO_4_1, KEY_STEREOCONFIGIDX_ALL_1, KEY_HBE_OFF, PARAMLIST_NOISEFILLING_ON, KEY_SBRPVC_OFF, 0, 4, KEY_TSD_ON},
    {PARAMLIST_AOT_42, 18000, 20999, 20000, PARAMLIST_BITRATEMODE_CBR, PARAMLIST_CHANNELCONFIG_MONO, PARAMLIST_TRANSPORTFORMAT_RAW, PARAMLIST_CONFIGSET_DASH, KEY_COREMODE_ALL_SWITCHED, KEY_OUTSR_LST_44100_48000_D44100_D48000, KEY_QUALITY_HIGH, KEY_SBRSIGNALING_EXPL_HIER, KEY_SBRRATIO_8_3, KEY_STEREOCONFIGIDX_NONE, KEY_HBE_OFF, PARAMLIST_NOISEFILLING_ON, KEY_SBRPVC_OFF, 0, 3, KEY_TSD_OFF},
    {PARAMLIST_AOT_42, 18000, 20999, 20000, PARAMLIST_BITRATEMODE_CBR, PARAMLIST_CHANNELCONFIG_MONO, PARAMLIST_TRANSPORTFORMAT_LATMLOAS, PARAMLIST_CONFIGSET_DASH, KEY_COREMODE_ALL_SWITCHED, KEY_OUTSR_LST_44100_48000_D44100_D48000, KEY_QUALITY_HIGH, KEY_SBRSIGNALING_EXPL_HIER, KEY_SBRRATIO_8_3, KEY_STEREOCONFIGIDX_NONE, KEY_HBE_OFF, PARAMLIST_NOISEFILLING_ON, KEY_SBRPVC_OFF, 0, 3, KEY_TSD_OFF},
    {PARAMLIST_AOT_42, 18000, 20999, 20000, PARAMLIST_BITRATEMODE_CBR, PARAMLIST_CHANNELCONFIG_STEREO, PARAMLIST_TRANSPORTFORMAT_RAW, PARAMLIST_CONFIGSET_DASH, KEY_COREMODE_ALL_SWITCHED, KEY_OUTSR_LST_44100_48000_D44100_D48000, KEY_QUALITY_HIGH, KEY_SBRSIGNALING_EXPL_HIER, KEY_SBRRATIO_8_3, KEY_STEREOCONFIGIDX_ALL_1, KEY_HBE_OFF, PARAMLIST_NOISEFILLING_ON, KEY_SBRPVC_OFF, 0, 4, KEY_TSD_ON},
    {PARAMLIST_AOT_42, 18000, 20999, 20000, PARAMLIST_BITRATEMODE_CBR, PARAMLIST_CHANNELCONFIG_STEREO, PARAMLIST_TRANSPORTFORMAT_LATMLOAS, PARAMLIST_CONFIGSET_DASH, KEY_COREMODE_ALL_SWITCHED, KEY_OUTSR_LST_44100_48000_D44100_D48000, KEY_QUALITY_HIGH, KEY_SBRSIGNALING_EXPL_HIER, KEY_SBRRATIO_8_3, KEY_STEREOCONFIGIDX_ALL_1, KEY_HBE_OFF, PARAMLIST_NOISEFILLING_ON, KEY_SBRPVC_OFF, 0, 4, KEY_TSD_ON},
    {PARAMLIST_AOT_42, 18000, 20999, 20000, PARAMLIST_BITRATEMODE_VBR0, PARAMLIST_CHANNELCONFIG_MONO, PARAMLIST_TRANSPORTFORMAT_RAW, PARAMLIST_CONFIGSET_DASH, KEY_COREMODE_ALL_SWITCHED, KEY_OUTSR_LST_44100_48000_D44100_D48000, KEY_QUALITY_HIGH, KEY_SBRSIGNALING_EXPL_HIER, KEY_SBRRATIO_8_3, KEY_STEREOCONFIGIDX_NONE, KEY_HBE_OFF, PARAMLIST_NOISEFILLING_ON, KEY_SBRPVC_OFF, 0, 4, KEY_TSD_OFF},
    {PARAMLIST_AOT_42, 18000, 20999, 20000, PARAMLIST_BITRATEMODE_VBR0, PARAMLIST_CHANNELCONFIG_MONO, PARAMLIST_TRANSPORTFORMAT_LATMLOAS, PARAMLIST_CONFIGSET_DASH, KEY_COREMODE_ALL_SWITCHED, KEY_OUTSR_LST_44100_48000_D44100_D48000, KEY_QUALITY_HIGH, KEY_SBRSIGNALING_EXPL_HIER, KEY_SBRRATIO_8_3, KEY_STEREOCONFIGIDX_NONE, KEY_HBE_OFF, PARAMLIST_NOISEFILLING_ON, KEY_SBRPVC_OFF, 0, 4, KEY_TSD_OFF},
    {PARAMLIST_AOT_42, 21000, 22999, 22000, PARAMLIST_BITRATEMODE_CBR, PARAMLIST_CHANNELCONFIG_MONO, PARAMLIST_TRANSPORTFORMAT_RAW, PARAMLIST_CONFIGSET_DASH, KEY_COREMODE_ALL_SWITCHED, KEY_OUTSR_LST_44100_48000_D44100_D48000, KEY_QUALITY_HIGH, KEY_SBRSIGNALING_EXPL_HIER, KEY_SBRRATIO_2_1, KEY_STEREOCONFIGIDX_NONE, KEY_HBE_OFF, PARAMLIST_NOISEFILLING_ON, KEY_SBRPVC_OFF, 0, 5, KEY_TSD_OFF},
    {PARAMLIST_AOT_42, 21000, 22999, 22000, PARAMLIST_BITRATEMODE_CBR, PARAMLIST_CHANNELCONFIG_MONO, PARAMLIST_TRANSPORTFORMAT_LATMLOAS, PARAMLIST_CONFIGSET_DASH, KEY_COREMODE_ALL_SWITCHED, KEY_OUTSR_LST_44100_48000_D44100_D48000, KEY_QUALITY_HIGH, KEY_SBRSIGNALING_EXPL_HIER, KEY_SBRRATIO_2_1, KEY_STEREOCONFIGIDX_NONE, KEY_HBE_OFF, PARAMLIST_NOISEFILLING_ON, KEY_SBRPVC_OFF, 0, 5, KEY_TSD_OFF},
    {PARAMLIST_AOT_42, 21000, 22999, 22000, PARAMLIST_BITRATEMODE_CBR, PARAMLIST_CHANNELCONFIG_STEREO, PARAMLIST_TRANSPORTFORMAT_RAW, PARAMLIST_CONFIGSET_DASH, KEY_COREMODE_ALL_SWITCHED, KEY_OUTSR_LST_44100_48000_D44100_D48000, KEY_QUALITY_HIGH, KEY_SBRSIGNALING_EXPL_HIER, KEY_SBRRATIO_8_3, KEY_STEREOCONFIGIDX_ALL_1, KEY_HBE_OFF, PARAMLIST_NOISEFILLING_ON, KEY_SBRPVC_OFF, 0, 4, KEY_TSD_ON},
    {PARAMLIST_AOT_42, 21000, 22999, 22000, PARAMLIST_BITRATEMODE_CBR, PARAMLIST_CHANNELCONFIG_STEREO, PARAMLIST_TRANSPORTFORMAT_LATMLOAS, PARAMLIST_CONFIGSET_DASH, KEY_COREMODE_ALL_SWITCHED, KEY_OUTSR_LST_44100_48000_D44100_D48000, KEY_QUALITY_HIGH, KEY_SBRSIGNALING_EXPL_HIER, KEY_SBRRATIO_8_3, KEY_STEREOCONFIGIDX_ALL_1, KEY_HBE_OFF, PARAMLIST_NOISEFILLING_ON, KEY_SBRPVC_OFF, 0, 4, KEY_TSD_ON},
    {PARAMLIST_AOT_42, 23000, 25999, 24000, PARAMLIST_BITRATEMODE_CBR, PARAMLIST_CHANNELCONFIG_MONO, PARAMLIST_TRANSPORTFORMAT_RAW, PARAMLIST_CONFIGSET_DASH, KEY_COREMODE_ALL_SWITCHED, KEY_OUTSR_LST_44100_48000_D44100_D48000, KEY_QUALITY_HIGH, KEY_SBRSIGNALING_EXPL_HIER, KEY_SBRRATIO_2_1, KEY_STEREOCONFIGIDX_NONE, KEY_HBE_OFF, PARAMLIST_NOISEFILLING_ON, KEY_SBRPVC_OFF, 0, 5, KEY_TSD_OFF},
    {PARAMLIST_AOT_42, 23000, 25999, 24000, PARAMLIST_BITRATEMODE_CBR, PARAMLIST_CHANNELCONFIG_MONO, PARAMLIST_TRANSPORTFORMAT_LATMLOAS, PARAMLIST_CONFIGSET_DASH, KEY_COREMODE_ALL_SWITCHED, KEY_OUTSR_LST_44100_48000_D44100_D48000, KEY_QUALITY_HIGH, KEY_SBRSIGNALING_EXPL_HIER, KEY_SBRRATIO_2_1, KEY_STEREOCONFIGIDX_NONE, KEY_HBE_OFF, PARAMLIST_NOISEFILLING_ON, KEY_SBRPVC_OFF, 0, 5, KEY_TSD_OFF},
    {PARAMLIST_AOT_42, 23000, 25999, 24000, PARAMLIST_BITRATEMODE_CBR, PARAMLIST_CHANNELCONFIG_STEREO, PARAMLIST_TRANSPORTFORMAT_RAW, PARAMLIST_CONFIGSET_DASH, KEY_COREMODE_ALL_SWITCHED, KEY_OUTSR_LST_44100_48000_D44100_D48000, KEY_QUALITY_HIGH, KEY_SBRSIGNALING_EXPL_HIER, KEY_SBRRATIO_8_3, KEY_STEREOCONFIGIDX_ALL_1, KEY_HBE_OFF, PARAMLIST_NOISEFILLING_ON, KEY_SBRPVC_OFF, 0, 5, KEY_TSD_ON},
    {PARAMLIST_AOT_42, 23000, 25999, 24000, PARAMLIST_BITRATEMODE_CBR, PARAMLIST_CHANNELCONFIG_STEREO, PARAMLIST_TRANSPORTFORMAT_LATMLOAS, PARAMLIST_CONFIGSET_DASH, KEY_COREMODE_ALL_SWITCHED, KEY_OUTSR_LST_44100_48000_D44100_D48000, KEY_QUALITY_HIGH, KEY_SBRSIGNALING_EXPL_HIER, KEY_SBRRATIO_8_3, KEY_STEREOCONFIGIDX_ALL_1, KEY_HBE_OFF, PARAMLIST_NOISEFILLING_ON, KEY_SBRPVC_OFF, 0, 5, KEY_TSD_ON},
    {PARAMLIST_AOT_42, 23000, 25999, 24000, PARAMLIST_BITRATEMODE_VBR0, PARAMLIST_CHANNELCONFIG_STEREO, PARAMLIST_TRANSPORTFORMAT_RAW, PARAMLIST_CONFIGSET_DASH, KEY_COREMODE_ALL_SWITCHED, KEY_OUTSR_LST_44100_48000_D44100_D48000, KEY_QUALITY_HIGH, KEY_SBRSIGNALING_EXPL_HIER, KEY_SBRRATIO_8_3, KEY_STEREOCONFIGIDX_ALL_1, KEY_HBE_OFF, PARAMLIST_NOISEFILLING_ON, KEY_SBRPVC_OFF, 0, 5, KEY_TSD_ON},
    {PARAMLIST_AOT_42, 23000, 25999, 24000, PARAMLIST_BITRATEMODE_VBR0, PARAMLIST_CHANNELCONFIG_STEREO, PARAMLIST_TRANSPORTFORMAT_LATMLOAS, PARAMLIST_CONFIGSET_DASH, KEY_COREMODE_ALL_SWITCHED, KEY_OUTSR_LST_44100_48000_D44100_D48000, KEY_QUALITY_HIGH, KEY_SBRSIGNALING_EXPL_HIER, KEY_SBRRATIO_8_3, KEY_STEREOCONFIGIDX_ALL_1, KEY_HBE_OFF, PARAMLIST_NOISEFILLING_ON, KEY_SBRPVC_OFF, 0, 5, KEY_TSD_ON},
    {PARAMLIST_AOT_42, 26000, 28999, 28000, PARAMLIST_BITRATEMODE_CBR, PARAMLIST_CHANNELCONFIG_MONO, PARAMLIST_TRANSPORTFORMAT_RAW, PARAMLIST_CONFIGSET_DASH, KEY_COREMODE_ALL_SWITCHED, KEY_OUTSR_LST_44100_48000_D44100_D48000, KEY_QUALITY_HIGH, KEY_SBRSIGNALING_EXPL_HIER, KEY_SBRRATIO_2_1, KEY_STEREOCONFIGIDX_NONE, KEY_HBE_OFF, PARAMLIST_NOISEFILLING_ON, KEY_SBRPVC_OFF, 0, 5, KEY_TSD_OFF},
    {PARAMLIST_AOT_42, 26000, 28999, 28000, PARAMLIST_BITRATEMODE_CBR, PARAMLIST_CHANNELCONFIG_MONO, PARAMLIST_TRANSPORTFORMAT_LATMLOAS, PARAMLIST_CONFIGSET_DASH, KEY_COREMODE_ALL_SWITCHED, KEY_OUTSR_LST_44100_48000_D44100_D48000, KEY_QUALITY_HIGH, KEY_SBRSIGNALING_EXPL_HIER, KEY_SBRRATIO_2_1, KEY_STEREOCONFIGIDX_NONE, KEY_HBE_OFF, PARAMLIST_NOISEFILLING_ON, KEY_SBRPVC_OFF, 0, 5, KEY_TSD_OFF},
    {PARAMLIST_AOT_42, 26000, 28999, 28000, PARAMLIST_BITRATEMODE_CBR, PARAMLIST_CHANNELCONFIG_STEREO, PARAMLIST_TRANSPORTFORMAT_RAW, PARAMLIST_CONFIGSET_DASH, KEY_COREMODE_ALL_SWITCHED, KEY_OUTSR_LST_44100_48000_D44100_D48000, KEY_QUALITY_HIGH, KEY_SBRSIGNALING_EXPL_HIER, KEY_SBRRATIO_8_3, KEY_STEREOCONFIGIDX_ALL_1, KEY_HBE_OFF, PARAMLIST_NOISEFILLING_ON, KEY_SBRPVC_OFF, 0, 5, KEY_TSD_ON},
    {PARAMLIST_AOT_42, 26000, 28999, 28000, PARAMLIST_BITRATEMODE_CBR, PARAMLIST_CHANNELCONFIG_STEREO, PARAMLIST_TRANSPORTFORMAT_LATMLOAS, PARAMLIST_CONFIGSET_DASH, KEY_COREMODE_ALL_SWITCHED, KEY_OUTSR_LST_44100_48000_D44100_D48000, KEY_QUALITY_HIGH, KEY_SBRSIGNALING_EXPL_HIER, KEY_SBRRATIO_8_3, KEY_STEREOCONFIGIDX_ALL_1, KEY_HBE_OFF, PARAMLIST_NOISEFILLING_ON, KEY_SBRPVC_OFF, 0, 5, KEY_TSD_ON},
    {PARAMLIST_AOT_42, 29000, 30999, 30000, PARAMLIST_BITRATEMODE_CBR, PARAMLIST_CHANNELCONFIG_MONO, PARAMLIST_TRANSPORTFORMAT_RAW, PARAMLIST_CONFIGSET_DASH, KEY_COREMODE_ALL_SWITCHED, KEY_OUTSR_LST_44100_48000_D44100_D48000, KEY_QUALITY_HIGH, KEY_SBRSIGNALING_EXPL_HIER, KEY_SBRRATIO_2_1, KEY_STEREOCONFIGIDX_NONE, KEY_HBE_OFF, PARAMLIST_NOISEFILLING_ON, KEY_SBRPVC_OFF, 0, 5, KEY_TSD_OFF},
    {PARAMLIST_AOT_42, 29000, 30999, 30000, PARAMLIST_BITRATEMODE_CBR, PARAMLIST_CHANNELCONFIG_MONO, PARAMLIST_TRANSPORTFORMAT_LATMLOAS, PARAMLIST_CONFIGSET_DASH, KEY_COREMODE_ALL_SWITCHED, KEY_OUTSR_LST_44100_48000_D44100_D48000, KEY_QUALITY_HIGH, KEY_SBRSIGNALING_EXPL_HIER, KEY_SBRRATIO_2_1, KEY_STEREOCONFIGIDX_NONE, KEY_HBE_OFF, PARAMLIST_NOISEFILLING_ON, KEY_SBRPVC_OFF, 0, 5, KEY_TSD_OFF},
    {PARAMLIST_AOT_42, 29000, 30999, 30000, PARAMLIST_BITRATEMODE_CBR, PARAMLIST_CHANNELCONFIG_STEREO, PARAMLIST_TRANSPORTFORMAT_RAW, PARAMLIST_CONFIGSET_DASH, KEY_COREMODE_ALL_SWITCHED, KEY_OUTSR_LST_44100_48000_D44100_D48000, KEY_QUALITY_HIGH, KEY_SBRSIGNALING_EXPL_HIER, KEY_SBRRATIO_8_3, KEY_STEREOCONFIGIDX_ALL_1, KEY_HBE_OFF, PARAMLIST_NOISEFILLING_ON, KEY_SBRPVC_OFF, 0, 5, KEY_TSD_ON},
    {PARAMLIST_AOT_42, 29000, 30999, 30000, PARAMLIST_BITRATEMODE_CBR, PARAMLIST_CHANNELCONFIG_STEREO, PARAMLIST_TRANSPORTFORMAT_LATMLOAS, PARAMLIST_CONFIGSET_DASH, KEY_COREMODE_ALL_SWITCHED, KEY_OUTSR_LST_44100_48000_D44100_D48000, KEY_QUALITY_HIGH, KEY_SBRSIGNALING_EXPL_HIER, KEY_SBRRATIO_8_3, KEY_STEREOCONFIGIDX_ALL_1, KEY_HBE_OFF, PARAMLIST_NOISEFILLING_ON, KEY_SBRPVC_OFF, 0, 5, KEY_TSD_ON},
    {PARAMLIST_AOT_42, 31000, 39999, 32000, PARAMLIST_BITRATEMODE_CBR, PARAMLIST_CHANNELCONFIG_MONO, PARAMLIST_TRANSPORTFORMAT_RAW, PARAMLIST_CONFIGSET_DASH, KEY_COREMODE_ALL_SWITCHED, KEY_OUTSR_LST_44100_48000_D44100_D48000, KEY_QUALITY_HIGH, KEY_SBRSIGNALING_EXPL_HIER, KEY_SBRRATIO_2_1, KEY_STEREOCONFIGIDX_NONE, KEY_HBE_OFF, PARAMLIST_NOISEFILLING_ON, KEY_SBRPVC_OFF, 0, 7, KEY_TSD_OFF},
    {PARAMLIST_AOT_42, 31000, 39999, 32000, PARAMLIST_BITRATEMODE_CBR, PARAMLIST_CHANNELCONFIG_MONO, PARAMLIST_TRANSPORTFORMAT_LATMLOAS, PARAMLIST_CONFIGSET_DASH, KEY_COREMODE_ALL_SWITCHED, KEY_OUTSR_LST_44100_48000_D44100_D48000, KEY_QUALITY_HIGH, KEY_SBRSIGNALING_EXPL_HIER, KEY_SBRRATIO_2_1, KEY_STEREOCONFIGIDX_NONE, KEY_HBE_OFF, PARAMLIST_NOISEFILLING_ON, KEY_SBRPVC_OFF, 0, 7, KEY_TSD_OFF},
    {PARAMLIST_AOT_42, 31000, 39999, 32000, PARAMLIST_BITRATEMODE_CBR, PARAMLIST_CHANNELCONFIG_STEREO, PARAMLIST_TRANSPORTFORMAT_RAW, PARAMLIST_CONFIGSET_DASH, KEY_COREMODE_ALL_SWITCHED, KEY_OUTSR_LST_44100_48000_D44100_D48000, KEY_QUALITY_HIGH, KEY_SBRSIGNALING_EXPL_HIER, KEY_SBRRATIO_8_3, KEY_STEREOCONFIGIDX_ALL_1, KEY_HBE_OFF, PARAMLIST_NOISEFILLING_ON, KEY_SBRPVC_OFF, 0, 6, KEY_TSD_ON},
    {PARAMLIST_AOT_42, 31000, 39999, 32000, PARAMLIST_BITRATEMODE_CBR, PARAMLIST_CHANNELCONFIG_STEREO, PARAMLIST_TRANSPORTFORMAT_LATMLOAS, PARAMLIST_CONFIGSET_DASH, KEY_COREMODE_ALL_SWITCHED, KEY_OUTSR_LST_44100_48000_D44100_D48000, KEY_QUALITY_HIGH, KEY_SBRSIGNALING_EXPL_HIER, KEY_SBRRATIO_8_3, KEY_STEREOCONFIGIDX_ALL_1, KEY_HBE_OFF, PARAMLIST_NOISEFILLING_ON, KEY_SBRPVC_OFF, 0, 6, KEY_TSD_ON},
    {PARAMLIST_AOT_42, 31000, 39999, 32000, PARAMLIST_BITRATEMODE_VBR1, PARAMLIST_CHANNELCONFIG_MONO, PARAMLIST_TRANSPORTFORMAT_RAW, PARAMLIST_CONFIGSET_DASH, KEY_COREMODE_ALL_SWITCHED, KEY_OUTSR_LST_44100_48000_D44100_D48000, KEY_QUALITY_HIGH, KEY_SBRSIGNALING_EXPL_HIER, KEY_SBRRATIO_2_1, KEY_STEREOCONFIGIDX_NONE, KEY_HBE_OFF, PARAMLIST_NOISEFILLING_ON, KEY_SBRPVC_OFF, 0, 7, KEY_TSD_OFF},
    {PARAMLIST_AOT_42, 31000, 39999, 32000, PARAMLIST_BITRATEMODE_VBR1, PARAMLIST_CHANNELCONFIG_MONO, PARAMLIST_TRANSPORTFORMAT_LATMLOAS, PARAMLIST_CONFIGSET_DASH, KEY_COREMODE_ALL_SWITCHED, KEY_OUTSR_LST_44100_48000_D44100_D48000, KEY_QUALITY_HIGH, KEY_SBRSIGNALING_EXPL_HIER, KEY_SBRRATIO_2_1, KEY_STEREOCONFIGIDX_NONE, KEY_HBE_OFF, PARAMLIST_NOISEFILLING_ON, KEY_SBRPVC_OFF, 0, 7, KEY_TSD_OFF},
    {PARAMLIST_AOT_42, 40000, 51999, 48000, PARAMLIST_BITRATEMODE_CBR, PARAMLIST_CHANNELCONFIG_MONO, PARAMLIST_TRANSPORTFORMAT_RAW, PARAMLIST_CONFIGSET_DASH, KEY_COREMODE_FD, KEY_OUTSR_LST_44100_48000_D44100_D48000, KEY_QUALITY_HIGH, KEY_SBRSIGNALING_EXPL_HIER, KEY_SBRRATIO_2_1, KEY_STEREOCONFIGIDX_NONE, KEY_HBE_OFF, PARAMLIST_NOISEFILLING_OFF, KEY_SBRPVC_OFF, 0, 7, KEY_TSD_OFF},
    {PARAMLIST_AOT_42, 40000, 51999, 48000, PARAMLIST_BITRATEMODE_CBR, PARAMLIST_CHANNELCONFIG_MONO, PARAMLIST_TRANSPORTFORMAT_LATMLOAS, PARAMLIST_CONFIGSET_DASH, KEY_COREMODE_FD, KEY_OUTSR_LST_44100_48000_D44100_D48000, KEY_QUALITY_HIGH, KEY_SBRSIGNALING_EXPL_HIER, KEY_SBRRATIO_2_1, KEY_STEREOCONFIGIDX_NONE, KEY_HBE_OFF, PARAMLIST_NOISEFILLING_OFF, KEY_SBRPVC_OFF, 0, 7, KEY_TSD_OFF},
    {PARAMLIST_AOT_42, 40000, 51999, 48000, PARAMLIST_BITRATEMODE_CBR, PARAMLIST_CHANNELCONFIG_STEREO, PARAMLIST_TRANSPORTFORMAT_RAW, PARAMLIST_CONFIGSET_DASH, KEY_COREMODE_FD, KEY_OUTSR_LST_44100_48000_D44100_D48000, KEY_QUALITY_HIGH, KEY_SBRSIGNALING_EXPL_HIER, KEY_SBRRATIO_2_1, KEY_STEREOCONFIGIDX_ALL_3, KEY_HBE_OFF, PARAMLIST_NOISEFILLING_OFF, KEY_SBRPVC_OFF, 0, 7, KEY_TSD_OFF},
    {PARAMLIST_AOT_42, 40000, 51999, 48000, PARAMLIST_BITRATEMODE_CBR, PARAMLIST_CHANNELCONFIG_STEREO, PARAMLIST_TRANSPORTFORMAT_LATMLOAS, PARAMLIST_CONFIGSET_DASH, KEY_COREMODE_FD, KEY_OUTSR_LST_44100_48000_D44100_D48000, KEY_QUALITY_HIGH, KEY_SBRSIGNALING_EXPL_HIER, KEY_SBRRATIO_2_1, KEY_STEREOCONFIGIDX_ALL_3, KEY_HBE_OFF, PARAMLIST_NOISEFILLING_OFF, KEY_SBRPVC_OFF, 0, 7, KEY_TSD_OFF},
    {PARAMLIST_AOT_42, 40000, 51999, 48000, PARAMLIST_BITRATEMODE_VBR1, PARAMLIST_CHANNELCONFIG_STEREO, PARAMLIST_TRANSPORTFORMAT_RAW, PARAMLIST_CONFIGSET_DASH, KEY_COREMODE_ALL_SWITCHED, KEY_OUTSR_LST_44100_48000_D44100_D48000, KEY_QUALITY_HIGH, KEY_SBRSIGNALING_EXPL_HIER, KEY_SBRRATIO_2_1, KEY_STEREOCONFIGIDX_ALL_1, KEY_HBE_OFF, PARAMLIST_NOISEFILLING_OFF, KEY_SBRPVC_OFF, 0, 7, KEY_TSD_OFF},
    {PARAMLIST_AOT_42, 40000, 51999, 48000, PARAMLIST_BITRATEMODE_VBR1, PARAMLIST_CHANNELCONFIG_STEREO, PARAMLIST_TRANSPORTFORMAT_LATMLOAS, PARAMLIST_CONFIGSET_DASH, KEY_COREMODE_ALL_SWITCHED, KEY_OUTSR_LST_44100_48000_D44100_D48000, KEY_QUALITY_HIGH, KEY_SBRSIGNALING_EXPL_HIER, KEY_SBRRATIO_2_1, KEY_STEREOCONFIGIDX_ALL_1, KEY_HBE_OFF, PARAMLIST_NOISEFILLING_OFF, KEY_SBRPVC_OFF, 0, 7, KEY_TSD_OFF},
    {PARAMLIST_AOT_42, 40000, 51999, 48000, PARAMLIST_BITRATEMODE_VBR2, PARAMLIST_CHANNELCONFIG_MONO, PARAMLIST_TRANSPORTFORMAT_RAW, PARAMLIST_CONFIGSET_DASH, KEY_COREMODE_FD, KEY_OUTSR_LST_44100_48000_D44100_D48000, KEY_QUALITY_HIGH, KEY_SBRSIGNALING_EXPL_HIER, KEY_SBRRATIO_2_1, KEY_STEREOCONFIGIDX_NONE, KEY_HBE_OFF, PARAMLIST_NOISEFILLING_OFF, KEY_SBRPVC_OFF, 0, 7, KEY_TSD_OFF},
    {PARAMLIST_AOT_42, 40000, 51999, 48000, PARAMLIST_BITRATEMODE_VBR2, PARAMLIST_CHANNELCONFIG_MONO, PARAMLIST_TRANSPORTFORMAT_LATMLOAS, PARAMLIST_CONFIGSET_DASH, KEY_COREMODE_FD, KEY_OUTSR_LST_44100_48000_D44100_D48000, KEY_QUALITY_HIGH, KEY_SBRSIGNALING_EXPL_HIER, KEY_SBRRATIO_2_1, KEY_STEREOCONFIGIDX_NONE, KEY_HBE_OFF, PARAMLIST_NOISEFILLING_OFF, KEY_SBRPVC_OFF, 0, 7, KEY_TSD_OFF},
    {PARAMLIST_AOT_42, 52000, 59999, 56000, PARAMLIST_BITRATEMODE_CBR, PARAMLIST_CHANNELCONFIG_MONO, PARAMLIST_TRANSPORTFORMAT_RAW, PARAMLIST_CONFIGSET_DASH, KEY_COREMODE_FD, KEY_OUTSR_LST_44100_48000_D44100_D48000, KEY_QUALITY_HIGH, KEY_SBRSIGNALING_EXPL_HIER, KEY_SBRRATIO_2_1, KEY_STEREOCONFIGIDX_NONE, KEY_HBE_OFF, PARAMLIST_NOISEFILLING_OFF, KEY_SBRPVC_OFF, 0, 7, KEY_TSD_OFF},
    {PARAMLIST_AOT_42, 52000, 59999, 56000, PARAMLIST_BITRATEMODE_CBR, PARAMLIST_CHANNELCONFIG_MONO, PARAMLIST_TRANSPORTFORMAT_LATMLOAS, PARAMLIST_CONFIGSET_DASH, KEY_COREMODE_FD, KEY_OUTSR_LST_44100_48000_D44100_D48000, KEY_QUALITY_HIGH, KEY_SBRSIGNALING_EXPL_HIER, KEY_SBRRATIO_2_1, KEY_STEREOCONFIGIDX_NONE, KEY_HBE_OFF, PARAMLIST_NOISEFILLING_OFF, KEY_SBRPVC_OFF, 0, 7, KEY_TSD_OFF},
    {PARAMLIST_AOT_42, 52000, 59999, 56000, PARAMLIST_BITRATEMODE_CBR, PARAMLIST_CHANNELCONFIG_STEREO, PARAMLIST_TRANSPORTFORMAT_RAW, PARAMLIST_CONFIGSET_DASH, KEY_COREMODE_FD, KEY_OUTSR_LST_44100_48000_D44100_D48000, KEY_QUALITY_HIGH, KEY_SBRSIGNALING_EXPL_HIER, KEY_SBRRATIO_2_1, KEY_STEREOCONFIGIDX_ALL_3, KEY_HBE_OFF, PARAMLIST_NOISEFILLING_OFF, KEY_SBRPVC_OFF, 0, 7, KEY_TSD_OFF},
    {PARAMLIST_AOT_42, 52000, 59999, 56000, PARAMLIST_BITRATEMODE_CBR, PARAMLIST_CHANNELCONFIG_STEREO, PARAMLIST_TRANSPORTFORMAT_LATMLOAS, PARAMLIST_CONFIGSET_DASH, KEY_COREMODE_FD, KEY_OUTSR_LST_44100_48000_D44100_D48000, KEY_QUALITY_HIGH, KEY_SBRSIGNALING_EXPL_HIER, KEY_SBRRATIO_2_1, KEY_STEREOCONFIGIDX_ALL_3, KEY_HBE_OFF, PARAMLIST_NOISEFILLING_OFF, KEY_SBRPVC_OFF, 0, 7, KEY_TSD_OFF},
    {PARAMLIST_AOT_42, 52000, 59999, 56000, PARAMLIST_BITRATEMODE_VBR3, PARAMLIST_CHANNELCONFIG_MONO, PARAMLIST_TRANSPORTFORMAT_RAW, PARAMLIST_CONFIGSET_DASH, KEY_COREMODE_FD, KEY_OUTSR_LST_44100_48000_D44100_D48000, KEY_QUALITY_HIGH, KEY_SBRSIGNALING_EXPL_HIER, KEY_SBRRATIO_NONE, KEY_STEREOCONFIGIDX_NONE, KEY_HBE_OFF, PARAMLIST_NOISEFILLING_OFF, KEY_SBRPVC_OFF, 0, 7, KEY_TSD_OFF},
    {PARAMLIST_AOT_42, 52000, 59999, 56000, PARAMLIST_BITRATEMODE_VBR3, PARAMLIST_CHANNELCONFIG_MONO, PARAMLIST_TRANSPORTFORMAT_LATMLOAS, PARAMLIST_CONFIGSET_DASH, KEY_COREMODE_FD, KEY_OUTSR_LST_44100_48000_D44100_D48000, KEY_QUALITY_HIGH, KEY_SBRSIGNALING_EXPL_HIER, KEY_SBRRATIO_NONE, KEY_STEREOCONFIGIDX_NONE, KEY_HBE_OFF, PARAMLIST_NOISEFILLING_OFF, KEY_SBRPVC_OFF, 0, 7, KEY_TSD_OFF},
    {PARAMLIST_AOT_42, 60000, 71999, 64000, PARAMLIST_BITRATEMODE_CBR, PARAMLIST_CHANNELCONFIG_MONO, PARAMLIST_TRANSPORTFORMAT_RAW, PARAMLIST_CONFIGSET_DASH, KEY_COREMODE_FD, KEY_OUTSR_LST_44100_48000_D44100_D48000, KEY_QUALITY_HIGH, KEY_SBRSIGNALING_EXPL_HIER, KEY_SBRRATIO_NONE, KEY_STEREOCONFIGIDX_NONE, KEY_HBE_OFF, PARAMLIST_NOISEFILLING_OFF, KEY_SBRPVC_OFF, 0, 7, KEY_TSD_OFF},
    {PARAMLIST_AOT_42, 60000, 71999, 64000, PARAMLIST_BITRATEMODE_CBR, PARAMLIST_CHANNELCONFIG_MONO, PARAMLIST_TRANSPORTFORMAT_LATMLOAS, PARAMLIST_CONFIGSET_DASH, KEY_COREMODE_FD, KEY_OUTSR_LST_44100_48000_D44100_D48000, KEY_QUALITY_HIGH, KEY_SBRSIGNALING_EXPL_HIER, KEY_SBRRATIO_NONE, KEY_STEREOCONFIGIDX_NONE, KEY_HBE_OFF, PARAMLIST_NOISEFILLING_OFF, KEY_SBRPVC_OFF, 0, 7, KEY_TSD_OFF},
    {PARAMLIST_AOT_42, 60000, 71999, 64000, PARAMLIST_BITRATEMODE_CBR, PARAMLIST_CHANNELCONFIG_STEREO, PARAMLIST_TRANSPORTFORMAT_RAW, PARAMLIST_CONFIGSET_DASH, KEY_COREMODE_FD, KEY_OUTSR_LST_44100_48000_D44100_D48000, KEY_QUALITY_HIGH, KEY_SBRSIGNALING_EXPL_HIER, KEY_SBRRATIO_2_1, KEY_STEREOCONFIGIDX_ALL_3, KEY_HBE_OFF, PARAMLIST_NOISEFILLING_OFF, KEY_SBRPVC_OFF, 0, 7, KEY_TSD_OFF},
    {PARAMLIST_AOT_42, 60000, 71999, 64000, PARAMLIST_BITRATEMODE_CBR, PARAMLIST_CHANNELCONFIG_STEREO, PARAMLIST_TRANSPORTFORMAT_LATMLOAS, PARAMLIST_CONFIGSET_DASH, KEY_COREMODE_FD, KEY_OUTSR_LST_44100_48000_D44100_D48000, KEY_QUALITY_HIGH, KEY_SBRSIGNALING_EXPL_HIER, KEY_SBRRATIO_2_1, KEY_STEREOCONFIGIDX_ALL_3, KEY_HBE_OFF, PARAMLIST_NOISEFILLING_OFF, KEY_SBRPVC_OFF, 0, 7, KEY_TSD_OFF},
    {PARAMLIST_AOT_42, 60000, 71999, 64000, PARAMLIST_BITRATEMODE_VBR2, PARAMLIST_CHANNELCONFIG_STEREO, PARAMLIST_TRANSPORTFORMAT_RAW, PARAMLIST_CONFIGSET_DASH, KEY_COREMODE_FD, KEY_OUTSR_LST_44100_48000_D44100_D48000, KEY_QUALITY_HIGH, KEY_SBRSIGNALING_EXPL_HIER, KEY_SBRRATIO_2_1, KEY_STEREOCONFIGIDX_ALL_3, KEY_HBE_OFF, PARAMLIST_NOISEFILLING_OFF, KEY_SBRPVC_OFF, 0, 7, KEY_TSD_OFF},
    {PARAMLIST_AOT_42, 60000, 71999, 64000, PARAMLIST_BITRATEMODE_VBR2, PARAMLIST_CHANNELCONFIG_STEREO, PARAMLIST_TRANSPORTFORMAT_LATMLOAS, PARAMLIST_CONFIGSET_DASH, KEY_COREMODE_FD, KEY_OUTSR_LST_44100_48000_D44100_D48000, KEY_QUALITY_HIGH, KEY_SBRSIGNALING_EXPL_HIER, KEY_SBRRATIO_2_1, KEY_STEREOCONFIGIDX_ALL_3, KEY_HBE_OFF, PARAMLIST_NOISEFILLING_OFF, KEY_SBRPVC_OFF, 0, 7, KEY_TSD_OFF},
    {PARAMLIST_AOT_42, 72000, 87999, 80000, PARAMLIST_BITRATEMODE_CBR, PARAMLIST_CHANNELCONFIG_MONO, PARAMLIST_TRANSPORTFORMAT_RAW, PARAMLIST_CONFIGSET_DASH, KEY_COREMODE_FD, KEY_OUTSR_LST_44100_48000_D44100_D48000, KEY_QUALITY_HIGH, KEY_SBRSIGNALING_EXPL_HIER, KEY_SBRRATIO_NONE, KEY_STEREOCONFIGIDX_NONE, KEY_HBE_OFF, PARAMLIST_NOISEFILLING_OFF, KEY_SBRPVC_OFF, 0, 7, KEY_TSD_OFF},
    {PARAMLIST_AOT_42, 72000, 87999, 80000, PARAMLIST_BITRATEMODE_CBR, PARAMLIST_CHANNELCONFIG_MONO, PARAMLIST_TRANSPORTFORMAT_LATMLOAS, PARAMLIST_CONFIGSET_DASH, KEY_COREMODE_FD, KEY_OUTSR_LST_44100_48000_D44100_D48000, KEY_QUALITY_HIGH, KEY_SBRSIGNALING_EXPL_HIER, KEY_SBRRATIO_NONE, KEY_STEREOCONFIGIDX_NONE, KEY_HBE_OFF, PARAMLIST_NOISEFILLING_OFF, KEY_SBRPVC_OFF, 0, 7, KEY_TSD_OFF},
    {PARAMLIST_AOT_42, 72000, 87999, 80000, PARAMLIST_BITRATEMODE_CBR, PARAMLIST_CHANNELCONFIG_STEREO, PARAMLIST_TRANSPORTFORMAT_RAW, PARAMLIST_CONFIGSET_DASH, KEY_COREMODE_FD, KEY_OUTSR_LST_44100_48000_D44100_D48000, KEY_QUALITY_HIGH, KEY_SBRSIGNALING_EXPL_HIER, KEY_SBRRATIO_NONE, KEY_STEREOCONFIGIDX_ALL_0, KEY_HBE_OFF, PARAMLIST_NOISEFILLING_OFF, KEY_SBRPVC_OFF, 0, 7, KEY_TSD_OFF},
    {PARAMLIST_AOT_42, 72000, 87999, 80000, PARAMLIST_BITRATEMODE_CBR, PARAMLIST_CHANNELCONFIG_STEREO, PARAMLIST_TRANSPORTFORMAT_LATMLOAS, PARAMLIST_CONFIGSET_DASH, KEY_COREMODE_FD, KEY_OUTSR_LST_44100_48000_D44100_D48000, KEY_QUALITY_HIGH, KEY_SBRSIGNALING_EXPL_HIER, KEY_SBRRATIO_NONE, KEY_STEREOCONFIGIDX_ALL_0, KEY_HBE_OFF, PARAMLIST_NOISEFILLING_OFF, KEY_SBRPVC_OFF, 0, 7, KEY_TSD_OFF},
    {PARAMLIST_AOT_42, 72000, 87999, 80000, PARAMLIST_BITRATEMODE_VBR4, PARAMLIST_CHANNELCONFIG_MONO, PARAMLIST_TRANSPORTFORMAT_RAW, PARAMLIST_CONFIGSET_DASH, KEY_COREMODE_FD, KEY_OUTSR_LST_44100_48000_D44100_D48000, KEY_QUALITY_HIGH, KEY_SBRSIGNALING_EXPL_HIER, KEY_SBRRATIO_NONE, KEY_STEREOCONFIGIDX_NONE, KEY_HBE_OFF, PARAMLIST_NOISEFILLING_OFF, KEY_SBRPVC_OFF, 0, 7, KEY_TSD_OFF},
    {PARAMLIST_AOT_42, 72000, 87999, 80000, PARAMLIST_BITRATEMODE_VBR4, PARAMLIST_CHANNELCONFIG_MONO, PARAMLIST_TRANSPORTFORMAT_LATMLOAS, PARAMLIST_CONFIGSET_DASH, KEY_COREMODE_FD, KEY_OUTSR_LST_44100_48000_D44100_D48000, KEY_QUALITY_HIGH, KEY_SBRSIGNALING_EXPL_HIER, KEY_SBRRATIO_NONE, KEY_STEREOCONFIGIDX_NONE, KEY_HBE_OFF, PARAMLIST_NOISEFILLING_OFF, KEY_SBRPVC_OFF, 0, 7, KEY_TSD_OFF},
    {PARAMLIST_AOT_42, 88000, 111999, 96000, PARAMLIST_BITRATEMODE_CBR, PARAMLIST_CHANNELCONFIG_MONO, PARAMLIST_TRANSPORTFORMAT_RAW, PARAMLIST_CONFIGSET_DASH, KEY_COREMODE_FD, KEY_OUTSR_LST_44100_48000_D44100_D48000, KEY_QUALITY_HIGH, KEY_SBRSIGNALING_EXPL_HIER, KEY_SBRRATIO_NONE, KEY_STEREOCONFIGIDX_NONE, KEY_HBE_OFF, PARAMLIST_NOISEFILLING_OFF, KEY_SBRPVC_OFF, 0, 7, KEY_TSD_OFF},
    {PARAMLIST_AOT_42, 88000, 111999, 96000, PARAMLIST_BITRATEMODE_CBR, PARAMLIST_CHANNELCONFIG_MONO, PARAMLIST_TRANSPORTFORMAT_LATMLOAS, PARAMLIST_CONFIGSET_DASH, KEY_COREMODE_FD, KEY_OUTSR_LST_44100_48000_D44100_D48000, KEY_QUALITY_HIGH, KEY_SBRSIGNALING_EXPL_HIER, KEY_SBRRATIO_NONE, KEY_STEREOCONFIGIDX_NONE, KEY_HBE_OFF, PARAMLIST_NOISEFILLING_OFF, KEY_SBRPVC_OFF, 0, 7, KEY_TSD_OFF},
    {PARAMLIST_AOT_42, 88000, 111999, 96000, PARAMLIST_BITRATEMODE_CBR, PARAMLIST_CHANNELCONFIG_STEREO, PARAMLIST_TRANSPORTFORMAT_RAW, PARAMLIST_CONFIGSET_DASH, KEY_COREMODE_FD, KEY_OUTSR_LST_44100_48000_D44100_D48000, KEY_QUALITY_HIGH, KEY_SBRSIGNALING_EXPL_HIER, KEY_SBRRATIO_NONE, KEY_STEREOCONFIGIDX_ALL_0, KEY_HBE_OFF, PARAMLIST_NOISEFILLING_OFF, KEY_SBRPVC_OFF, 0, 7, KEY_TSD_OFF},
    {PARAMLIST_AOT_42, 88000, 111999, 96000, PARAMLIST_BITRATEMODE_CBR, PARAMLIST_CHANNELCONFIG_STEREO, PARAMLIST_TRANSPORTFORMAT_LATMLOAS, PARAMLIST_CONFIGSET_DASH, KEY_COREMODE_FD, KEY_OUTSR_LST_44100_48000_D44100_D48000, KEY_QUALITY_HIGH, KEY_SBRSIGNALING_EXPL_HIER, KEY_SBRRATIO_NONE, KEY_STEREOCONFIGIDX_ALL_0, KEY_HBE_OFF, PARAMLIST_NOISEFILLING_OFF, KEY_SBRPVC_OFF, 0, 7, KEY_TSD_OFF},
    {PARAMLIST_AOT_42, 88000, 111999, 96000, PARAMLIST_BITRATEMODE_VBR3, PARAMLIST_CHANNELCONFIG_STEREO, PARAMLIST_TRANSPORTFORMAT_RAW, PARAMLIST_CONFIGSET_DASH, KEY_COREMODE_FD, KEY_OUTSR_LST_44100_48000_D44100_D48000, KEY_QUALITY_HIGH, KEY_SBRSIGNALING_EXPL_HIER, KEY_SBRRATIO_NONE, KEY_STEREOCONFIGIDX_ALL_0, KEY_HBE_OFF, PARAMLIST_NOISEFILLING_OFF, KEY_SBRPVC_OFF, 0, 7, KEY_TSD_OFF},
    {PARAMLIST_AOT_42, 88000, 111999, 96000, PARAMLIST_BITRATEMODE_VBR3, PARAMLIST_CHANNELCONFIG_STEREO, PARAMLIST_TRANSPORTFORMAT_LATMLOAS, PARAMLIST_CONFIGSET_DASH, KEY_COREMODE_FD, KEY_OUTSR_LST_44100_48000_D44100_D48000, KEY_QUALITY_HIGH, KEY_SBRSIGNALING_EXPL_HIER, KEY_SBRRATIO_NONE, KEY_STEREOCONFIGIDX_ALL_0, KEY_HBE_OFF, PARAMLIST_NOISEFILLING_OFF, KEY_SBRPVC_OFF, 0, 7, KEY_TSD_OFF},
    {PARAMLIST_AOT_42, 88000, 111999, 96000, PARAMLIST_BITRATEMODE_VBR5, PARAMLIST_CHANNELCONFIG_MONO, PARAMLIST_TRANSPORTFORMAT_RAW, PARAMLIST_CONFIGSET_DASH, KEY_COREMODE_FD, KEY_OUTSR_LST_44100_48000_D44100_D48000, KEY_QUALITY_HIGH, KEY_SBRSIGNALING_EXPL_HIER, KEY_SBRRATIO_NONE, KEY_STEREOCONFIGIDX_NONE, KEY_HBE_OFF, PARAMLIST_NOISEFILLING_OFF, KEY_SBRPVC_OFF, 0, 7, KEY_TSD_OFF},
    {PARAMLIST_AOT_42, 88000, 111999, 96000, PARAMLIST_BITRATEMODE_VBR5, PARAMLIST_CHANNELCONFIG_MONO, PARAMLIST_TRANSPORTFORMAT_LATMLOAS, PARAMLIST_CONFIGSET_DASH, KEY_COREMODE_FD, KEY_OUTSR_LST_44100_48000_D44100_D48000, KEY_QUALITY_HIGH, KEY_SBRSIGNALING_EXPL_HIER, KEY_SBRRATIO_NONE, KEY_STEREOCONFIGIDX_NONE, KEY_HBE_OFF, PARAMLIST_NOISEFILLING_OFF, KEY_SBRPVC_OFF, 0, 7, KEY_TSD_OFF},
    {PARAMLIST_AOT_42, 112000, 163920, 128000, PARAMLIST_BITRATEMODE_CBR, PARAMLIST_CHANNELCONFIG_MONO, PARAMLIST_TRANSPORTFORMAT_RAW, PARAMLIST_CONFIGSET_DASH, KEY_COREMODE_FD, KEY_OUTSR_LST_44100_48000_D44100_D48000, KEY_QUALITY_HIGH, KEY_SBRSIGNALING_EXPL_HIER, KEY_SBRRATIO_NONE, KEY_STEREOCONFIGIDX_NONE, KEY_HBE_OFF, PARAMLIST_NOISEFILLING_OFF, KEY_SBRPVC_OFF, 0, 7, KEY_TSD_OFF},
    {PARAMLIST_AOT_42, 112000, 163920, 128000, PARAMLIST_BITRATEMODE_CBR, PARAMLIST_CHANNELCONFIG_MONO, PARAMLIST_TRANSPORTFORMAT_LATMLOAS, PARAMLIST_CONFIGSET_DASH, KEY_COREMODE_FD, KEY_OUTSR_LST_44100_48000_D44100_D48000, KEY_QUALITY_HIGH, KEY_SBRSIGNALING_EXPL_HIER, KEY_SBRRATIO_NONE, KEY_STEREOCONFIGIDX_NONE, KEY_HBE_OFF, PARAMLIST_NOISEFILLING_OFF, KEY_SBRPVC_OFF, 0, 7, KEY_TSD_OFF},
    {PARAMLIST_AOT_42, 112000, 163920, 128000, PARAMLIST_BITRATEMODE_CBR, PARAMLIST_CHANNELCONFIG_STEREO, PARAMLIST_TRANSPORTFORMAT_RAW, PARAMLIST_CONFIGSET_DASH, KEY_COREMODE_FD, KEY_OUTSR_LST_44100_48000_D44100_D48000, KEY_QUALITY_HIGH, KEY_SBRSIGNALING_EXPL_HIER, KEY_SBRRATIO_NONE, KEY_STEREOCONFIGIDX_ALL_0, KEY_HBE_OFF, PARAMLIST_NOISEFILLING_OFF, KEY_SBRPVC_OFF, 0, 7, KEY_TSD_OFF},
    {PARAMLIST_AOT_42, 112000, 163920, 128000, PARAMLIST_BITRATEMODE_CBR, PARAMLIST_CHANNELCONFIG_STEREO, PARAMLIST_TRANSPORTFORMAT_LATMLOAS, PARAMLIST_CONFIGSET_DASH, KEY_COREMODE_FD, KEY_OUTSR_LST_44100_48000_D44100_D48000, KEY_QUALITY_HIGH, KEY_SBRSIGNALING_EXPL_HIER, KEY_SBRRATIO_NONE, KEY_STEREOCONFIGIDX_ALL_0, KEY_HBE_OFF, PARAMLIST_NOISEFILLING_OFF, KEY_SBRPVC_OFF, 0, 7, KEY_TSD_OFF},
    {PARAMLIST_AOT_42, 112000, 163920, 128000, PARAMLIST_BITRATEMODE_VBR4, PARAMLIST_CHANNELCONFIG_STEREO, PARAMLIST_TRANSPORTFORMAT_RAW, PARAMLIST_CONFIGSET_DASH, KEY_COREMODE_FD, KEY_OUTSR_LST_44100_48000_D44100_D48000, KEY_QUALITY_HIGH, KEY_SBRSIGNALING_EXPL_HIER, KEY_SBRRATIO_NONE, KEY_STEREOCONFIGIDX_ALL_0, KEY_HBE_OFF, PARAMLIST_NOISEFILLING_OFF, KEY_SBRPVC_OFF, 0, 7, KEY_TSD_OFF},
    {PARAMLIST_AOT_42, 112000, 163920, 128000, PARAMLIST_BITRATEMODE_VBR4, PARAMLIST_CHANNELCONFIG_STEREO, PARAMLIST_TRANSPORTFORMAT_LATMLOAS, PARAMLIST_CONFIGSET_DASH, KEY_COREMODE_FD, KEY_OUTSR_LST_44100_48000_D44100_D48000, KEY_QUALITY_HIGH, KEY_SBRSIGNALING_EXPL_HIER, KEY_SBRRATIO_NONE, KEY_STEREOCONFIGIDX_ALL_0, KEY_HBE_OFF, PARAMLIST_NOISEFILLING_OFF, KEY_SBRPVC_OFF, 0, 7, KEY_TSD_OFF},
    {PARAMLIST_AOT_42, 112000, 163920, 128000, PARAMLIST_BITRATEMODE_VBR6, PARAMLIST_CHANNELCONFIG_MONO, PARAMLIST_TRANSPORTFORMAT_RAW, PARAMLIST_CONFIGSET_DASH, KEY_COREMODE_FD, KEY_OUTSR_LST_44100_48000_D44100_D48000, KEY_QUALITY_HIGH, KEY_SBRSIGNALING_EXPL_HIER, KEY_SBRRATIO_NONE, KEY_STEREOCONFIGIDX_NONE, KEY_HBE_OFF, PARAMLIST_NOISEFILLING_OFF, KEY_SBRPVC_OFF, 0, 7, KEY_TSD_OFF},
    {PARAMLIST_AOT_42, 112000, 163920, 128000, PARAMLIST_BITRATEMODE_VBR6, PARAMLIST_CHANNELCONFIG_MONO, PARAMLIST_TRANSPORTFORMAT_LATMLOAS, PARAMLIST_CONFIGSET_DASH, KEY_COREMODE_FD, KEY_OUTSR_LST_44100_48000_D44100_D48000, KEY_QUALITY_HIGH, KEY_SBRSIGNALING_EXPL_HIER, KEY_SBRRATIO_NONE, KEY_STEREOCONFIGIDX_NONE, KEY_HBE_OFF, PARAMLIST_NOISEFILLING_OFF, KEY_SBRPVC_OFF, 0, 7, KEY_TSD_OFF},
    {PARAMLIST_AOT_42, 163921, 192000, 128000, PARAMLIST_BITRATEMODE_CBR, PARAMLIST_CHANNELCONFIG_STEREO, PARAMLIST_TRANSPORTFORMAT_RAW, PARAMLIST_CONFIGSET_DASH, KEY_COREMODE_FD, KEY_OUTSR_LST_44100_48000_D44100_D48000, KEY_QUALITY_HIGH, KEY_SBRSIGNALING_EXPL_HIER, KEY_SBRRATIO_NONE, KEY_STEREOCONFIGIDX_ALL_0, KEY_HBE_OFF, PARAMLIST_NOISEFILLING_OFF, KEY_SBRPVC_OFF, 0, 7, KEY_TSD_OFF},
    {PARAMLIST_AOT_42, 163921, 192000, 128000, PARAMLIST_BITRATEMODE_CBR, PARAMLIST_CHANNELCONFIG_STEREO, PARAMLIST_TRANSPORTFORMAT_LATMLOAS, PARAMLIST_CONFIGSET_DASH, KEY_COREMODE_FD, KEY_OUTSR_LST_44100_48000_D44100_D48000, KEY_QUALITY_HIGH, KEY_SBRSIGNALING_EXPL_HIER, KEY_SBRRATIO_NONE, KEY_STEREOCONFIGIDX_ALL_0, KEY_HBE_OFF, PARAMLIST_NOISEFILLING_OFF, KEY_SBRPVC_OFF, 0, 7, KEY_TSD_OFF},
    {PARAMLIST_AOT_42, 163921, 192000, 128000, PARAMLIST_BITRATEMODE_VBR5, PARAMLIST_CHANNELCONFIG_STEREO, PARAMLIST_TRANSPORTFORMAT_RAW, PARAMLIST_CONFIGSET_DASH, KEY_COREMODE_FD, KEY_OUTSR_LST_44100_48000_D44100_D48000, KEY_QUALITY_HIGH, KEY_SBRSIGNALING_EXPL_HIER, KEY_SBRRATIO_NONE, KEY_STEREOCONFIGIDX_ALL_0, KEY_HBE_OFF, PARAMLIST_NOISEFILLING_OFF, KEY_SBRPVC_OFF, 0, 7, KEY_TSD_OFF},
    {PARAMLIST_AOT_42, 163921, 192000, 128000, PARAMLIST_BITRATEMODE_VBR5, PARAMLIST_CHANNELCONFIG_STEREO, PARAMLIST_TRANSPORTFORMAT_LATMLOAS, PARAMLIST_CONFIGSET_DASH, KEY_COREMODE_FD, KEY_OUTSR_LST_44100_48000_D44100_D48000, KEY_QUALITY_HIGH, KEY_SBRSIGNALING_EXPL_HIER, KEY_SBRRATIO_NONE, KEY_STEREOCONFIGIDX_ALL_0, KEY_HBE_OFF, PARAMLIST_NOISEFILLING_OFF, KEY_SBRPVC_OFF, 0, 7, KEY_TSD_OFF},
    {PARAMLIST_AOT_42, 192001, 264000, 256000, PARAMLIST_BITRATEMODE_CBR, PARAMLIST_CHANNELCONFIG_STEREO, PARAMLIST_TRANSPORTFORMAT_RAW, PARAMLIST_CONFIGSET_DASH, KEY_COREMODE_FD, KEY_OUTSR_LST_44100_48000_D44100_D48000, KEY_QUALITY_HIGH, KEY_SBRSIGNALING_EXPL_HIER, KEY_SBRRATIO_NONE, KEY_STEREOCONFIGIDX_ALL_0, KEY_HBE_OFF, PARAMLIST_NOISEFILLING_OFF, KEY_SBRPVC_OFF, 0, 7, KEY_TSD_OFF},
    {PARAMLIST_AOT_42, 192001, 264000, 256000, PARAMLIST_BITRATEMODE_CBR, PARAMLIST_CHANNELCONFIG_STEREO, PARAMLIST_TRANSPORTFORMAT_LATMLOAS, PARAMLIST_CONFIGSET_DASH, KEY_COREMODE_FD, KEY_OUTSR_LST_44100_48000_D44100_D48000, KEY_QUALITY_HIGH, KEY_SBRSIGNALING_EXPL_HIER, KEY_SBRRATIO_NONE, KEY_STEREOCONFIGIDX_ALL_0, KEY_HBE_OFF, PARAMLIST_NOISEFILLING_OFF, KEY_SBRPVC_OFF, 0, 7, KEY_TSD_OFF},
    {PARAMLIST_AOT_42, 192001, 264000, 256000, PARAMLIST_BITRATEMODE_VBR6, PARAMLIST_CHANNELCONFIG_STEREO, PARAMLIST_TRANSPORTFORMAT_RAW, PARAMLIST_CONFIGSET_DASH, KEY_COREMODE_FD, KEY_OUTSR_LST_44100_48000_D44100_D48000, KEY_QUALITY_HIGH, KEY_SBRSIGNALING_EXPL_HIER, KEY_SBRRATIO_NONE, KEY_STEREOCONFIGIDX_ALL_0, KEY_HBE_OFF, PARAMLIST_NOISEFILLING_OFF, KEY_SBRPVC_OFF, 0, 7, KEY_TSD_OFF},
    {PARAMLIST_AOT_42, 192001, 264000, 256000, PARAMLIST_BITRATEMODE_VBR6, PARAMLIST_CHANNELCONFIG_STEREO, PARAMLIST_TRANSPORTFORMAT_LATMLOAS, PARAMLIST_CONFIGSET_DASH, KEY_COREMODE_FD, KEY_OUTSR_LST_44100_48000_D44100_D48000, KEY_QUALITY_HIGH, KEY_SBRSIGNALING_EXPL_HIER, KEY_SBRRATIO_NONE, KEY_STEREOCONFIGIDX_ALL_0, KEY_HBE_OFF, PARAMLIST_NOISEFILLING_OFF, KEY_SBRPVC_OFF, 0, 7, KEY_TSD_OFF},
    {PARAMLIST_AOT_42, 264001, 288000, 280000, PARAMLIST_BITRATEMODE_CBR, PARAMLIST_CHANNELCONFIG_STEREO, PARAMLIST_TRANSPORTFORMAT_RAW, PARAMLIST_CONFIGSET_DASH, KEY_COREMODE_FD, KEY_OUTSR_LST_44100_48000_D44100_D48000, KEY_QUALITY_HIGH, KEY_SBRSIGNALING_EXPL_HIER, KEY_SBRRATIO_NONE, KEY_STEREOCONFIGIDX_ALL_0, KEY_HBE_OFF, PARAMLIST_NOISEFILLING_OFF, KEY_SBRPVC_OFF, 0, 7, KEY_TSD_OFF},
    {PARAMLIST_AOT_42, 264001, 288000, 280000, PARAMLIST_BITRATEMODE_CBR, PARAMLIST_CHANNELCONFIG_STEREO, PARAMLIST_TRANSPORTFORMAT_LATMLOAS, PARAMLIST_CONFIGSET_DASH, KEY_COREMODE_FD, KEY_OUTSR_LST_44100_48000_D44100_D48000, KEY_QUALITY_HIGH, KEY_SBRSIGNALING_EXPL_HIER, KEY_SBRRATIO_NONE, KEY_STEREOCONFIGIDX_ALL_0, KEY_HBE_OFF, PARAMLIST_NOISEFILLING_OFF, KEY_SBRPVC_OFF, 0, 7, KEY_TSD_OFF},
    {PARAMLIST_AOT_42, 288001, 313999, 308000, PARAMLIST_BITRATEMODE_CBR, PARAMLIST_CHANNELCONFIG_STEREO, PARAMLIST_TRANSPORTFORMAT_RAW, PARAMLIST_CONFIGSET_DASH, KEY_COREMODE_FD, KEY_OUTSR_LST_44100_48000_D44100_D48000, KEY_QUALITY_HIGH, KEY_SBRSIGNALING_EXPL_HIER, KEY_SBRRATIO_NONE, KEY_STEREOCONFIGIDX_ALL_0, KEY_HBE_OFF, PARAMLIST_NOISEFILLING_OFF, KEY_SBRPVC_OFF, 0, 7, KEY_TSD_OFF},
    {PARAMLIST_AOT_42, 288001, 313999, 308000, PARAMLIST_BITRATEMODE_CBR, PARAMLIST_CHANNELCONFIG_STEREO, PARAMLIST_TRANSPORTFORMAT_LATMLOAS, PARAMLIST_CONFIGSET_DASH, KEY_COREMODE_FD, KEY_OUTSR_LST_44100_48000_D44100_D48000, KEY_QUALITY_HIGH, KEY_SBRSIGNALING_EXPL_HIER, KEY_SBRRATIO_NONE, KEY_STEREOCONFIGIDX_ALL_0, KEY_HBE_OFF, PARAMLIST_NOISEFILLING_OFF, KEY_SBRPVC_OFF, 0, 7, KEY_TSD_OFF},
    {PARAMLIST_AOT_42, 314000, 384000, 320000, PARAMLIST_BITRATEMODE_CBR, PARAMLIST_CHANNELCONFIG_STEREO, PARAMLIST_TRANSPORTFORMAT_RAW, PARAMLIST_CONFIGSET_DASH, KEY_COREMODE_FD, KEY_OUTSR_LST_44100_48000_D44100_D48000, KEY_QUALITY_HIGH, KEY_SBRSIGNALING_EXPL_HIER, KEY_SBRRATIO_NONE, KEY_STEREOCONFIGIDX_ALL_0, KEY_HBE_OFF, PARAMLIST_NOISEFILLING_OFF, KEY_SBRPVC_OFF, 0, 7, KEY_TSD_OFF},
    {PARAMLIST_AOT_42, 314000, 384000, 320000, PARAMLIST_BITRATEMODE_CBR, PARAMLIST_CHANNELCONFIG_STEREO, PARAMLIST_TRANSPORTFORMAT_LATMLOAS, PARAMLIST_CONFIGSET_DASH, KEY_COREMODE_FD, KEY_OUTSR_LST_44100_48000_D44100_D48000, KEY_QUALITY_HIGH, KEY_SBRSIGNALING_EXPL_HIER, KEY_SBRRATIO_NONE, KEY_STEREOCONFIGIDX_ALL_0, KEY_HBE_OFF, PARAMLIST_NOISEFILLING_OFF, KEY_SBRPVC_OFF, 0, 7, KEY_TSD_OFF},
    {PARAMLIST_AOT_42, 384001, 399999, 390000, PARAMLIST_BITRATEMODE_CBR, PARAMLIST_CHANNELCONFIG_STEREO, PARAMLIST_TRANSPORTFORMAT_RAW, PARAMLIST_CONFIGSET_DASH, KEY_COREMODE_FD, KEY_OUTSR_LST_44100_48000_D44100_D48000, KEY_QUALITY_HIGH, KEY_SBRSIGNALING_EXPL_HIER, KEY_SBRRATIO_NONE, KEY_STEREOCONFIGIDX_ALL_0, KEY_HBE_OFF, PARAMLIST_NOISEFILLING_OFF, KEY_SBRPVC_OFF, 0, 7, KEY_TSD_OFF},
    {PARAMLIST_AOT_42, 384001, 399999, 390000, PARAMLIST_BITRATEMODE_CBR, PARAMLIST_CHANNELCONFIG_STEREO, PARAMLIST_TRANSPORTFORMAT_LATMLOAS, PARAMLIST_CONFIGSET_DASH, KEY_COREMODE_FD, KEY_OUTSR_LST_44100_48000_D44100_D48000, KEY_QUALITY_HIGH, KEY_SBRSIGNALING_EXPL_HIER, KEY_SBRRATIO_NONE, KEY_STEREOCONFIGIDX_ALL_0, KEY_HBE_OFF, PARAMLIST_NOISEFILLING_OFF, KEY_SBRPVC_OFF, 0, 7, KEY_TSD_OFF},

};

ENCCONFIGCTAB_RETURN_CODE main_aot_42_dash_ossCheck(
    PARAMLIST_INSTANCE_HANDLE const hInputParamList,
    PARAMLIST_INSTANCE_HANDLE hOutputParamList,
    int const key) {
  ENCCONFIGCTAB_RETURN_CODE retCode = ENCCONFIGCTAB_NO_ERROR;
  HANDLE_ERROR_INFO errorInfo = noError;

  PARAM_INSTANCE_HANDLE param_aot = NULL;
  PARAM_INSTANCE_HANDLE param_bitratemin = NULL;
  PARAM_INSTANCE_HANDLE param_bitratemax = NULL;
  PARAM_INSTANCE_HANDLE param_bitrate = NULL;
  PARAM_INSTANCE_HANDLE param_bitratemode = NULL;
  PARAM_INSTANCE_HANDLE param_channelconfig = NULL;
  PARAM_INSTANCE_HANDLE param_transportformat = NULL;
  PARAM_INSTANCE_HANDLE param_configset = NULL;

  PARAMLIST_AOT aot = PARAMLIST_AOT_INVALID;
  PARAMLIST_BITRATE bitratemin = PARAMLIST_BITRATE_INVALID;
  PARAMLIST_BITRATE bitratemax = PARAMLIST_BITRATE_INVALID;
  PARAMLIST_BITRATE bitrate = PARAMLIST_BITRATE_INVALID;
  PARAMLIST_BITRATEMODE bitratemode = PARAMLIST_BITRATEMODE_INVALID;
  PARAMLIST_CHANNELCONFIG channelconfig = PARAMLIST_CHANNELCONFIG_INVALID;
  PARAMLIST_TRANSPORTFORMAT transportformat = PARAMLIST_TRANSPORTFORMAT_INVALID;
  PARAMLIST_CONFIGSET configset = PARAMLIST_CONFIGSET_INVALID;

  int i, found = 0;
  int tableSize = sizeof(main_aot_42_dash_oss) / sizeof(MAIN_AOT_42_DASH_OSS);
  int tableSizeDefault = sizeof(main_aot_42_dash_oss_default) / sizeof(MAIN_AOT_42_DASH_OSS_DEFAULT);

  if (errorInfo == noError) {
    errorInfo = iisParamListGetParam(hInputParamList, PARAMLIST_PARAMETER_AOT, &param_aot);
    if (param_aot) aot = (PARAMLIST_AOT)param_aot->paramValue._int;
  }

  if (errorInfo == noError) {
    errorInfo = iisParamListGetParam(hInputParamList, PARAMLIST_PARAMETER_BITRATEMIN, &param_bitratemin);
    if (param_bitratemin) bitratemin = (PARAMLIST_BITRATE)param_bitratemin->paramValue._int;
  }

  if (errorInfo == noError) {
    errorInfo = iisParamListGetParam(hInputParamList, PARAMLIST_PARAMETER_BITRATEMAX, &param_bitratemax);
    if (param_bitratemax) bitratemax = (PARAMLIST_BITRATE)param_bitratemax->paramValue._int;
  }

  if (errorInfo == noError) {
    errorInfo = iisParamListGetParam(hInputParamList, PARAMLIST_PARAMETER_BITRATE, &param_bitrate);
    if (param_bitrate) bitrate = (PARAMLIST_BITRATE)param_bitrate->paramValue._int;
  }

  if (errorInfo == noError) {
    errorInfo = iisParamListGetParam(hInputParamList, PARAMLIST_PARAMETER_BITRATEMODE, &param_bitratemode);
    if (param_bitratemode) bitratemode = (PARAMLIST_BITRATEMODE)param_bitratemode->paramValue._int;
  }

  if (errorInfo == noError) {
    errorInfo = iisParamListGetParam(hInputParamList, PARAMLIST_PARAMETER_CHANNELCONFIG, &param_channelconfig);
    if (param_channelconfig) channelconfig = (PARAMLIST_CHANNELCONFIG)param_channelconfig->paramValue._int;
  }

  if (errorInfo == noError) {
    errorInfo = iisParamListGetParam(hInputParamList, PARAMLIST_PARAMETER_TRANSPORTFORMAT, &param_transportformat);
    if (param_transportformat) transportformat = (PARAMLIST_TRANSPORTFORMAT)param_transportformat->paramValue._int;
  }

  if (errorInfo == noError) {
    errorInfo = iisParamListGetParam(hInputParamList, PARAMLIST_PARAMETER_CONFIGSET, &param_configset);
    if (param_configset) configset = (PARAMLIST_CONFIGSET)param_configset->paramValue._int;
  }

  AVOID_COMPILER_WARNING(aot);
  AVOID_COMPILER_WARNING(bitratemin);
  AVOID_COMPILER_WARNING(bitratemax);
  AVOID_COMPILER_WARNING(bitrate);
  AVOID_COMPILER_WARNING(bitratemode);
  AVOID_COMPILER_WARNING(channelconfig);
  AVOID_COMPILER_WARNING(transportformat);
  AVOID_COMPILER_WARNING(configset);

  AVOID_COMPILER_WARNING(key);

  for (i = 0; i < tableSize; i++) {
    if (1 && ((int)(main_aot_42_dash_oss[i].aot) == (int)aot) && ((int)(main_aot_42_dash_oss[i].bitratemin) <= (int)bitrate) && ((int)(main_aot_42_dash_oss[i].bitratemax) >= (int)bitrate) && ((int)(main_aot_42_dash_oss[i].bitratemode) == (int)bitratemode) && ((int)(main_aot_42_dash_oss[i].channelconfig) == (int)channelconfig) && ((int)(main_aot_42_dash_oss[i].transportformat) == (int)transportformat) && ((int)(main_aot_42_dash_oss[i].configset) == (int)configset)

    ) {
      PARAM_INSTANCE param;
      PARAM_INSTANCE_HANDLE param_advanced = NULL;

      int advanced = 0;
      AVOID_COMPILER_WARNING(param)
      AVOID_COMPILER_WARNING(param_advanced)
      AVOID_COMPILER_WARNING(advanced)

      iisParamListAddParam(hOutputParamList, param_aot, PARAMLIST_MODE_REPLACE);
      iisParamListAddParam(hOutputParamList, param_bitrate, PARAMLIST_MODE_REPLACE);
      iisParamListAddParam(hOutputParamList, param_bitratemode, PARAMLIST_MODE_REPLACE);
      iisParamListAddParam(hOutputParamList, param_channelconfig, PARAMLIST_MODE_REPLACE);
      iisParamListAddParam(hOutputParamList, param_transportformat, PARAMLIST_MODE_REPLACE);
      iisParamListAddParam(hOutputParamList, param_configset, PARAMLIST_MODE_REPLACE);

      param.paramFormat = PARAM_INT;
      param.paramLength = 1;
      param.paramTag = PARAMLIST_PARAMETER_NOISEFILLING;
      param.paramValue._int = main_aot_42_dash_oss[i].noisefilling;
      iisParamListAddParam(hOutputParamList, &param, PARAMLIST_MODE_REPLACE);

      param.paramFormat = PARAM_INT;
      param.paramLength = 1;
      param.paramTag = PARAMLIST_PARAMETER_SBRRAISEDXOVERFREQ;
      param.paramValue._int = main_aot_42_dash_oss[i].sbrraisedxoverfreq;
      iisParamListAddParam(hOutputParamList, &param, PARAMLIST_MODE_REPLACE);

      param.paramFormat = PARAM_INT;
      param.paramLength = 1;
      param.paramTag = PARAMLIST_PARAMETER_ACELPMODEINDEX;
      param.paramValue._int = main_aot_42_dash_oss[i].acelpmodeindex;
      iisParamListAddParam(hOutputParamList, &param, PARAMLIST_MODE_REPLACE);

      if ((errorInfo == noError) && (retCode < ENCCONFIGCTAB_ERROR_FIRST)) {
        retCode = tab_coremodeCheck(hInputParamList, hOutputParamList, main_aot_42_dash_oss[i].keycoremode);
      }
      if ((errorInfo == noError) && (retCode < ENCCONFIGCTAB_ERROR_FIRST)) {
        retCode = tab_outsamplerate_ossCheck(hInputParamList, hOutputParamList, main_aot_42_dash_oss[i].keyoutsamplerate);
      }
      if ((errorInfo == noError) && (retCode < ENCCONFIGCTAB_ERROR_FIRST)) {
        retCode = tab_qualityCheck(hInputParamList, hOutputParamList, main_aot_42_dash_oss[i].keyquality);
      }
      if ((errorInfo == noError) && (retCode < ENCCONFIGCTAB_ERROR_FIRST)) {
        retCode = tab_sbrsignalingCheck(hInputParamList, hOutputParamList, main_aot_42_dash_oss[i].keysbrsignaling);
      }
      if ((errorInfo == noError) && (retCode < ENCCONFIGCTAB_ERROR_FIRST)) {
        retCode = tab_sbrratioCheck(hInputParamList, hOutputParamList, main_aot_42_dash_oss[i].keysbrratio);
      }
      if ((errorInfo == noError) && (retCode < ENCCONFIGCTAB_ERROR_FIRST)) {
        retCode = tab_stereoconfigidxCheck(hInputParamList, hOutputParamList, main_aot_42_dash_oss[i].keystereoconfigidx);
      }
      if ((errorInfo == noError) && (retCode < ENCCONFIGCTAB_ERROR_FIRST)) {
        retCode = tab_hbeCheck(hInputParamList, hOutputParamList, main_aot_42_dash_oss[i].keyhbe);
      }
      if ((errorInfo == noError) && (retCode < ENCCONFIGCTAB_ERROR_FIRST)) {
        retCode = tab_sbrpvcCheck(hInputParamList, hOutputParamList, main_aot_42_dash_oss[i].keysbrpvc);
      }
      if ((errorInfo == noError) && (retCode < ENCCONFIGCTAB_ERROR_FIRST)) {
        retCode = tab_tsdCheck(hInputParamList, hOutputParamList, main_aot_42_dash_oss[i].keytsd);
      }

      if (retCode >= ENCCONFIGCTAB_ERROR_FIRST) {
        break;
      }

      if (errorInfo == noError) {
        errorInfo = iisParamListGetParam(hInputParamList, PARAMLIST_PARAMETER_ADVANCED, &param_advanced);
        if (param_advanced) advanced = param_advanced->paramValue._int;

        if (advanced > 0) {
          PARAM_INSTANCE_HANDLE paramAdd = NULL;
          int add = 0;
          AVOID_COMPILER_WARNING(paramAdd)
          AVOID_COMPILER_WARNING(add)
        }
      }

      if (errorInfo != noError) break;

      found++;
    }
  }

  if ((errorInfo == noError) && (found == 0 && aot == PARAMLIST_AOT_INVALID && bitratemin == PARAMLIST_BITRATE_INVALID && bitratemax == PARAMLIST_BITRATE_INVALID && bitrate == PARAMLIST_BITRATE_INVALID && bitratemode == PARAMLIST_BITRATEMODE_INVALID && channelconfig == PARAMLIST_CHANNELCONFIG_INVALID && transportformat == PARAMLIST_TRANSPORTFORMAT_INVALID && configset == PARAMLIST_CONFIGSET_INVALID

                                 )) {
    found = 0;

    for (i = 0; i < tableSizeDefault; i++) {
      if (1 && ((int)(main_aot_42_dash_oss_default[i].keycoremode) == key) && ((int)(main_aot_42_dash_oss_default[i].keyoutsamplerate) == key) && ((int)(main_aot_42_dash_oss_default[i].keyquality) == key) && ((int)(main_aot_42_dash_oss_default[i].keysbrsignaling) == key) && ((int)(main_aot_42_dash_oss_default[i].keysbrratio) == key) && ((int)(main_aot_42_dash_oss_default[i].keystereoconfigidx) == key) && ((int)(main_aot_42_dash_oss_default[i].keyhbe) == key) && ((int)(main_aot_42_dash_oss_default[i].keysbrpvc) == key) && ((int)(main_aot_42_dash_oss_default[i].keytsd) == key)

      ) {
        PARAM_INSTANCE param;

        param.paramFormat = PARAM_INT;
        param.paramLength = 1;
        param.paramTag = PARAMLIST_PARAMETER_AOT;
        param.paramValue._int = main_aot_42_dash_oss_default[i].aot;
        iisParamListAddParam(hOutputParamList, &param, PARAMLIST_MODE_REPLACE);

        param.paramFormat = PARAM_INT;
        param.paramLength = 1;
        param.paramTag = PARAMLIST_PARAMETER_BITRATEMIN;
        param.paramValue._int = main_aot_42_dash_oss_default[i].bitratemin;
        iisParamListAddParam(hOutputParamList, &param, PARAMLIST_MODE_REPLACE);

        param.paramFormat = PARAM_INT;
        param.paramLength = 1;
        param.paramTag = PARAMLIST_PARAMETER_BITRATEMAX;
        param.paramValue._int = main_aot_42_dash_oss_default[i].bitratemax;
        iisParamListAddParam(hOutputParamList, &param, PARAMLIST_MODE_REPLACE);

        param.paramFormat = PARAM_INT;
        param.paramLength = 1;
        param.paramTag = PARAMLIST_PARAMETER_BITRATE;
        param.paramValue._int = main_aot_42_dash_oss_default[i].bitrate;
        iisParamListAddParam(hOutputParamList, &param, PARAMLIST_MODE_REPLACE);

        param.paramFormat = PARAM_INT;
        param.paramLength = 1;
        param.paramTag = PARAMLIST_PARAMETER_BITRATEMODE;
        param.paramValue._int = main_aot_42_dash_oss_default[i].bitratemode;
        iisParamListAddParam(hOutputParamList, &param, PARAMLIST_MODE_REPLACE);

        param.paramFormat = PARAM_INT;
        param.paramLength = 1;
        param.paramTag = PARAMLIST_PARAMETER_CHANNELCONFIG;
        param.paramValue._int = main_aot_42_dash_oss_default[i].channelconfig;
        iisParamListAddParam(hOutputParamList, &param, PARAMLIST_MODE_REPLACE);

        param.paramFormat = PARAM_INT;
        param.paramLength = 1;
        param.paramTag = PARAMLIST_PARAMETER_TRANSPORTFORMAT;
        param.paramValue._int = main_aot_42_dash_oss_default[i].transportformat;
        iisParamListAddParam(hOutputParamList, &param, PARAMLIST_MODE_REPLACE);

        param.paramFormat = PARAM_INT;
        param.paramLength = 1;
        param.paramTag = PARAMLIST_PARAMETER_CONFIGSET;
        param.paramValue._int = main_aot_42_dash_oss_default[i].configset;
        iisParamListAddParam(hOutputParamList, &param, PARAMLIST_MODE_REPLACE);

        param.paramFormat = PARAM_INT;
        param.paramLength = 1;
        param.paramTag = PARAMLIST_PARAMETER_NOISEFILLING;
        param.paramValue._int = main_aot_42_dash_oss_default[i].noisefilling;
        iisParamListAddParam(hOutputParamList, &param, PARAMLIST_MODE_REPLACE);

        param.paramFormat = PARAM_INT;
        param.paramLength = 1;
        param.paramTag = PARAMLIST_PARAMETER_SBRRAISEDXOVERFREQ;
        param.paramValue._int = main_aot_42_dash_oss_default[i].sbrraisedxoverfreq;
        iisParamListAddParam(hOutputParamList, &param, PARAMLIST_MODE_REPLACE);

        param.paramFormat = PARAM_INT;
        param.paramLength = 1;
        param.paramTag = PARAMLIST_PARAMETER_ACELPMODEINDEX;
        param.paramValue._int = main_aot_42_dash_oss_default[i].acelpmodeindex;
        iisParamListAddParam(hOutputParamList, &param, PARAMLIST_MODE_REPLACE);

        if ((errorInfo == noError) && (retCode < ENCCONFIGCTAB_ERROR_FIRST)) {
          retCode = tab_coremodeCheck(hInputParamList, hOutputParamList, main_aot_42_dash_oss_default[i].keycoremode);
        }
        if ((errorInfo == noError) && (retCode < ENCCONFIGCTAB_ERROR_FIRST)) {
          retCode = tab_outsamplerate_ossCheck(hInputParamList, hOutputParamList, main_aot_42_dash_oss_default[i].keyoutsamplerate);
        }
        if ((errorInfo == noError) && (retCode < ENCCONFIGCTAB_ERROR_FIRST)) {
          retCode = tab_qualityCheck(hInputParamList, hOutputParamList, main_aot_42_dash_oss_default[i].keyquality);
        }
        if ((errorInfo == noError) && (retCode < ENCCONFIGCTAB_ERROR_FIRST)) {
          retCode = tab_sbrsignalingCheck(hInputParamList, hOutputParamList, main_aot_42_dash_oss_default[i].keysbrsignaling);
        }
        if ((errorInfo == noError) && (retCode < ENCCONFIGCTAB_ERROR_FIRST)) {
          retCode = tab_sbrratioCheck(hInputParamList, hOutputParamList, main_aot_42_dash_oss_default[i].keysbrratio);
        }
        if ((errorInfo == noError) && (retCode < ENCCONFIGCTAB_ERROR_FIRST)) {
          retCode = tab_stereoconfigidxCheck(hInputParamList, hOutputParamList, main_aot_42_dash_oss_default[i].keystereoconfigidx);
        }
        if ((errorInfo == noError) && (retCode < ENCCONFIGCTAB_ERROR_FIRST)) {
          retCode = tab_hbeCheck(hInputParamList, hOutputParamList, main_aot_42_dash_oss_default[i].keyhbe);
        }
        if ((errorInfo == noError) && (retCode < ENCCONFIGCTAB_ERROR_FIRST)) {
          retCode = tab_sbrpvcCheck(hInputParamList, hOutputParamList, main_aot_42_dash_oss_default[i].keysbrpvc);
        }
        if ((errorInfo == noError) && (retCode < ENCCONFIGCTAB_ERROR_FIRST)) {
          retCode = tab_tsdCheck(hInputParamList, hOutputParamList, main_aot_42_dash_oss_default[i].keytsd);
        }

        found++;
        break;
      }
    }
  }

  if (retCode < ENCCONFIGCTAB_ERROR_FIRST) {
    if (errorInfo == noError) {
      if (found == 0) {
        retCode = ENCCONFIGCTAB_ERROR_NO_CONFIG_FOUND;
      } else if (found > 1) {
        retCode = ENCCONFIGCTAB_ERROR_UNKOWN;
      } else {
        retCode = ENCCONFIGCTAB_INFO_CONFIG_FOUND;
      }
    } else {
      retCode = ENCCONFIGCTAB_ERROR_UNKOWN;
    }
  }

  return retCode;
}

int main_aot_42_dash_ossIsValid(
    int const key,
    int const value) {
  int i, retVal = 0;
  int tableSize = sizeof(main_aot_42_dash_oss) / sizeof(MAIN_AOT_42_DASH_OSS);

  AVOID_COMPILER_WARNING(key);

  for (i = 0; i < tableSize; i++) {
    if (1 && ((int)(main_aot_42_dash_oss[i].aot) == value) && ((int)(main_aot_42_dash_oss[i].bitratemin) == value) && ((int)(main_aot_42_dash_oss[i].bitratemax) == value) && ((int)(main_aot_42_dash_oss[i].bitrate) == value) && ((int)(main_aot_42_dash_oss[i].bitratemode) == value) && ((int)(main_aot_42_dash_oss[i].channelconfig) == value) && ((int)(main_aot_42_dash_oss[i].transportformat) == value) && ((int)(main_aot_42_dash_oss[i].configset) == value) && ((int)(main_aot_42_dash_oss[i].keycoremode) == value) && ((int)(main_aot_42_dash_oss[i].keyoutsamplerate) == value) && ((int)(main_aot_42_dash_oss[i].keyquality) == value) && ((int)(main_aot_42_dash_oss[i].keysbrsignaling) == value) && ((int)(main_aot_42_dash_oss[i].keysbrratio) == value) && ((int)(main_aot_42_dash_oss[i].keystereoconfigidx) == value) && ((int)(main_aot_42_dash_oss[i].keyhbe) == value) && ((int)(main_aot_42_dash_oss[i].keysbrpvc) == value) && ((int)(main_aot_42_dash_oss[i].keytsd) == value)

    ) {
      retVal = 1;
      break;
    }
  }

  return retVal;
}
