
/* -----------------------------------------------------------------------------
Software Copyright License for The Fraunhofer FDK Extended High Efficiency AAC
Encoder Software for Android

© Copyright 1995 - 2025 Fraunhofer-Gesellschaft zur Förderung der angewandten
Forschung e.V. and Contributors
All rights reserved.

1.    INTRODUCTION

The Fraunhofer FDK Extended High Efficiency AAC Encoder Software for Android
("FDK Extended High Efficiency AAC Encoder") is software that implements the
encoding of digital audio according to the MPEG-D Unified Speech and Audio
Coding (USAC) standard and MPEG-D Dynamic Range Control (DRC) standard. This FDK
Extended High Efficiency AAC Encoder Software is intended to be used on a wide
variety of Android devices. It is technically not suited to encode content for
digital radio broadcasting services, including DRM and similar standards.

Patent licenses for necessary patent claims for the FDK Extended High Efficiency
AAC Encoder Software (including those of Fraunhofer), for the use in commercial
products and services, may be obtained from the respective patent owners
individually and/or from Via Licensing Alliance (www.via-la.com).

Fraunhofer supports the development of Extended High Efficiency AAC products and
services by offering additional software, documentation, and technical advice.
In addition, it operates the xHE-AAC Trademark Program to ease interoperability
testing of end products. Please visit http://www.xhe-aac.com for more
information.

2.    COPYRIGHT LICENSE

Redistribution and use in source and binary forms, with or without modification,
are permitted without payment of copyright license fees, provided that you
satisfy the following conditions:

You must retain the complete text of this software license in redistributions of
the FDK Extended High Efficiency AAC Encoder Software or your modifications
thereto in source code form.

You must retain the complete text of this software license in the documentation
and/or other materials provided with redistributions of the FDK Extended High
Efficiency AAC Encoder Software or your modifications thereto in binary form.
You must make available free of charge copies of the complete source code of the
FDK Extended High Efficiency AAC Encoder Software and your modifications thereto
to recipients of copies in binary form.

The name of Fraunhofer may not be used to endorse or promote products derived
from this software without prior written permission.

You may not charge copyright license fees for anyone to use, copy or distribute
the FDK Extended High Efficiency AAC Encoder Software or your modifications
thereto.

Your modified versions of the FDK Extended High Efficiency AAC Encoder Software
must carry prominent notices stating that you changed the software and the date
of any change. For modified versions of the FDK Extended High Efficiency AAC
Encoder Software, the term "Fraunhofer FDK Extended High Efficiency AAC Encoder
Software for Android" must be replaced by the term "Third-Party Modified Version
of the Fraunhofer FDK Extended High Efficiency AAC Encoder Software for
Android."

3.    NO PATENT LICENSE

NO EXPRESS OR IMPLIED LICENSES TO ANY PATENT CLAIMS, including without
limitation the patents of Fraunhofer, ARE GRANTED BY THIS SOFTWARE LICENSE.
Fraunhofer provides no warranty for patent non-infringement with respect to this
software. You may use this FDK Extended High Efficiency AAC Encoder Software or
modifications thereto only for purposes that are authorized by appropriate
patent licenses.

4.    DISCLAIMER

This FDK Extended High Efficiency AAC Encoder Software is provided by Fraunhofer
on behalf of the copyright holders and contributors "AS IS" and WITHOUT ANY
EXPRESS OR IMPLIED WARRANTIES, including but not limited to the implied
warranties of merchantability and fitness for a particular purpose. IN NO EVENT
SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE for any direct, indirect,
incidental, special, exemplary, or consequential damages, including but not
limited to procurement of substitute goods or services; loss of use, data, or
profits, or business interruption, however caused and on any theory of
liability, whether in contract, strict liability, or tort (including
negligence), arising in any way out of the use of this software, even if advised
of the possibility of such damage.

5.    CONTACT INFORMATION

Fraunhofer Institute for Integrated Circuits IIS
Attention: Division Audio and Media Technologies - FDK Extended High Efficiency
AAC Encoder
Am Wolfsmantel 33
91058 Erlangen, Germany

www.iis.fraunhofer.de/amm
amm-info@iis.fraunhofer.de
----------------------------------------------------------------------------- */

#ifndef IISPARAMLIST_H
#define IISPARAMLIST_H

#ifdef __cplusplus
extern "C" {
#endif

#include <limits.h>

#include "iisutillib.h"
#include "iisParam.h"

#define PARAMLIST_MAX_ALLOWED_TAG 0x90000000

typedef unsigned int PARAMLIST_UNIFIEDSTEREO;
typedef unsigned int PARAMLIST_SBRSTEREO;
typedef unsigned int PARAMLIST_SBRSTARTFREQ;
typedef unsigned int PARAMLIST_SBRSTOPFREQ;
typedef unsigned int PARAMLIST_SBRRAISEDXOVERFREQ;
typedef unsigned int PARAMLIST_ACELPMODEINDEX;
typedef float PARAMLIST_ACELPFSCALE;
typedef unsigned int PARAMLIST_BITRATE;
typedef unsigned int PARAMLIST_AUDIOBANDWIDTH;
typedef unsigned int PARAMLIST_STREAMID;
typedef unsigned int PARAMLIST_NUMAUDIOPREROLL;

#define PARAMLIST_BANDWIDTH_INVALID INT_MAX
#define PARAMLIST_BITRATE_INVALID INT_MAX
#define PARAMLIST_INSAMPLERATE_INVALID INT_MAX
#define PARAMLIST_OUTSAMPLERATE_INVALID INT_MAX
#define PARAMLIST_LOWDELAYSWITCHING_INVALID INT_MAX

typedef enum {
  PARAMLIST_AOT_42 = 0x0010003,
  PARAMLIST_AOT_INVALID = 0xaf1ffff
} PARAMLIST_AOT;

typedef enum {
  PARAMLIST_ERROR_NO_ERROR,
  PARAMLIST_ERROR_NEW_PARAM,
  PARAMLIST_ERROR_NEW_LIST,
  PARAMLIST_ERROR_DELETE,
  PARAMLIST_ERROR_ITERATE,
  PARAMLIST_ERROR_COMPARE,
  PARAMLIST_ERROR_COPY,
  PARAMLIST_ERROR_SEC
} PARAMLIST_ERROR_CODE;

typedef enum {
  PARAMLIST_SAMPLERATE_192000 = 192000,
  PARAMLIST_SAMPLERATE_176400 = 176400,
  PARAMLIST_SAMPLERATE_96000 = 96000,
  PARAMLIST_SAMPLERATE_88200 = 88200,
  PARAMLIST_SAMPLERATE_76800 = 76800,
  PARAMLIST_SAMPLERATE_70560 = 70560,
  PARAMLIST_SAMPLERATE_64000 = 64000,
  PARAMLIST_SAMPLERATE_58800 = 58800,
  PARAMLIST_SAMPLERATE_48000 = 48000,
  PARAMLIST_SAMPLERATE_44100 = 44100,
  PARAMLIST_SAMPLERATE_40000 = 40000,
  PARAMLIST_SAMPLERATE_38400 = 38400,
  PARAMLIST_SAMPLERATE_35280 = 35280,
  PARAMLIST_SAMPLERATE_32000 = 32000,
  PARAMLIST_SAMPLERATE_29400 = 29400,
  PARAMLIST_SAMPLERATE_24000 = 24000,
  PARAMLIST_SAMPLERATE_22050 = 22050,
  PARAMLIST_SAMPLERATE_19200 = 19200,
  PARAMLIST_SAMPLERATE_17640 = 17640,
  PARAMLIST_SAMPLERATE_16000 = 16000,
  PARAMLIST_SAMPLERATE_14700 = 14700,
  PARAMLIST_SAMPLERATE_12800 = 12800,
  PARAMLIST_SAMPLERATE_12000 = 12000,
  PARAMLIST_SAMPLERATE_11760 = 11760,
  PARAMLIST_SAMPLERATE_11025 = 11025,
  PARAMLIST_SAMPLERATE_9600 = 9600,
  PARAMLIST_SAMPLERATE_8820 = 8820,
  PARAMLIST_SAMPLERATE_8000 = 8000,
  PARAMLIST_SAMPLERATE_7350 = 7350,
  PARAMLIST_SAMPLERATE_6000 = 6000,
  PARAMLIST_SAMPLERATE_INVALID = 0xaff1fff
} PARAMLIST_SAMPLERATE;

typedef enum {
  PARAMLIST_CHANNELCONFIG_MONO = 0x0000100,
  PARAMLIST_CHANNELCONFIG_STEREO = 0x0000101,
  PARAMLIST_CHANNELCONFIG_INVALID = 0xafff1ff
} PARAMLIST_CHANNELCONFIG;

typedef enum {
  PARAMLIST_QUALITY_FAST = 0x00000010,
  PARAMLIST_QUALITY_MEDIUM = 0x00000011,
  PARAMLIST_QUALITY_HIGH = 0x00000012,
  PARAMLIST_QUALITY_HIGHEST = 0x00000013,
  PARAMLIST_QUALITY_INVALID = 0x7fffff1f
} PARAMLIST_QUALITY;

typedef enum {
  PARAMLIST_HBE_ON = 0x20000000,
  PARAMLIST_HBE_OFF = 0x20000001,
  PARAMLIST_HBE_INVALID = 0x7fffffff
} PARAMLIST_HBE;

typedef enum {
  PARAMLIST_SBR_ON = 0x02000000,
  PARAMLIST_SBR_OFF = 0x02000001,
  PARAMLIST_SBR_INVALID = 0x72ffffff
} PARAMLIST_SBR;

typedef enum {
  PARAMLIST_GRANULELENGTH_768 = 0x00200000,
  PARAMLIST_GRANULELENGTH_960 = 0x00200001,
  PARAMLIST_GRANULELENGTH_1024 = 0x00200002,
  PARAMLIST_GRANULELENGTH_INVALID = 0x7f2fffff
} PARAMLIST_GRANULELENGTH;

typedef enum {
  PARAMLIST_FRAMESAMPLES_768 = 0x00202000,
  PARAMLIST_FRAMESAMPLES_960 = 0x00202001,
  PARAMLIST_FRAMESAMPLES_1024 = 0x00202002,
  PARAMLIST_FRAMESAMPLES_1920 = 0x00202005,
  PARAMLIST_FRAMESAMPLES_2048 = 0x00202003,
  PARAMLIST_FRAMESAMPLES_4096 = 0x00202004,
  PARAMLIST_FRAMESAMPLES_INVALID = 0x7f2f2fff
} PARAMLIST_FRAMESAMPLES;

typedef enum {
  PARAMLIST_TRANSPORTFORMAT_RAW = 0x00020000,
  PARAMLIST_TRANSPORTFORMAT_ADTS = 0x00020002,
  PARAMLIST_TRANSPORTFORMAT_LATM = 0x00020003,
  PARAMLIST_TRANSPORTFORMAT_LATMLOAS = 0x00020004,
  PARAMLIST_TRANSPORTFORMAT_INVALID = 0x7ff2ffff
} PARAMLIST_TRANSPORTFORMAT;

typedef enum {
  PARAMLIST_COREMODE_FD = 0x00002000,
  PARAMLIST_COREMODE_LPD = 0x00002001,
  PARAMLIST_COREMODE_SWITCHED = 0x00002002,
  PARAMLIST_COREMODE_INVALID = 0x7fff2fff
} PARAMLIST_COREMODE;

typedef enum {
  PARAMLIST_MPS212_ON = 0x00000200,
  PARAMLIST_MPS212_OFF = 0x00000201,
  PARAMLIST_MPS212_INVALID = 0x7ffff2ff
} PARAMLIST_MPS212;

typedef enum {
  PARAMLIST_NOISEFILLING_ON = 0x00000300,
  PARAMLIST_NOISEFILLING_OFF = 0x00000301,
  PARAMLIST_NOISEFILLING_INVALID = 0x7ffff3ff
} PARAMLIST_NOISEFILLING;

typedef enum {
  PARAMLIST_PULSESEARCH_ENHANCED_OFF = 0x02000000,
  PARAMLIST_PULSESEARCH_ENHANCED_ON = 0x02000020,
  PARAMLIST_PULSESEARCH_ENHANCED_INVALID = 0x7ffff3ff
} PARAMLIST_PULSESEARCH_ENHANCED;

typedef enum {
  PARAMLIST_RAP_ON_DEMAND_ADVANCED_MODE_OFF = 0,
  PARAMLIST_RAP_ON_DEMAND_ADVANCED_MODE_ON = 1,
  PARAMLIST_RAP_ON_DEMAND_ADVANCED_MODE_INVALID = -1
} PARAMLIST_RAP_ON_DEMAND_ADVANCED_MODE;

typedef enum {
  PARAMLIST_SBRRATIO_NONE = 0x00000200,
  PARAMLIST_SBRRATIO_2_1 = 0x00000201,
  PARAMLIST_SBRRATIO_4_1 = 0x00000202,
  PARAMLIST_SBRRATIO_8_3 = 0x00000203,
  PARAMLIST_SBRRATIO_1_1 = 0x00000204,
  PARAMLIST_SBRRATIO_INVALID = 0x7ffff2ff
} PARAMLIST_SBRRATIO;

typedef enum {
  PARAMLIST_STEREOCONFIGIDX_NONE = 0x00000300,
  PARAMLIST_STEREOCONFIGIDX_0 = 0x00000301,
  PARAMLIST_STEREOCONFIGIDX_1 = 0x00000302,
  PARAMLIST_STEREOCONFIGIDX_2 = 0x00000303,
  PARAMLIST_STEREOCONFIGIDX_3 = 0x00000304,
  PARAMLIST_STEREOCONFIGIDX_INVALID = 0x7ffff3ff
} PARAMLIST_STEREOCONFIGIDX;

typedef enum {
  PARAMLIST_TSD_ON = 0x00000020,
  PARAMLIST_TSD_OFF = 0x00000021,
  PARAMLIST_TSD_INVALID = 0x72ffffff
} PARAMLIST_TSD;

typedef enum {
  PARAMLIST_SBRPVC_ON = 0x00000030,
  PARAMLIST_SBRPVC_OFF = 0x00000031,
  PARAMLIST_SBRPVC_INVALID = 0x73ffffff
} PARAMLIST_SBRPVC;

typedef enum {
  PARAMLIST_SBRFIXBORDERFORINDEPFLAG_ON = 0x00000060,
  PARAMLIST_SBRFIXBORDERFORINDEPFLAG_OFF = 0x00000061,
  PARAMLIST_SBRFIXBORDERFORINDEPFLAG_INVALID = 0x76ffffff
} PARAMLIST_SBRFIXBORDERFORINDEPFLAG;

typedef enum {
  PARAMLIST_MPEG2AAC_ON = 0x00000090,
  PARAMLIST_MPEG2AAC_OFF = 0x00000091,
  PARAMLIST_MPEG2AAC_INVALID = 0x79ffffff
} PARAMLIST_MPEG2AAC;

typedef enum {
  PARAMLIST_DISABLELOUDNESS_ON = 0x00000080,
  PARAMLIST_DISABLELOUDNESS_OFF = 0x00000081,
  PARAMLIST_DISABLELOUDNESS_INVALID = 0x78ffffff
} PARAMLIST_DISABLELOUDNESS;

typedef enum {
  PARAMLIST_MPEGSHIGHRATEMODE_ON = 0x00000050,
  PARAMLIST_MPEGSHIGHRATEMODE_OFF = 0x00000051,
  PARAMLIST_MPEGSHIGHRATEMODE_INVALID = 0x75ffffff
} PARAMLIST_MPEGSHIGHRATEMODE;

typedef enum {
  PARAMLIST_BITRATEMODE_CBR = 0x30000000,
  PARAMLIST_BITRATEMODE_VBR1 = 0x30000001,
  PARAMLIST_BITRATEMODE_VBR2 = 0x30000002,
  PARAMLIST_BITRATEMODE_VBR3 = 0x30000003,
  PARAMLIST_BITRATEMODE_VBR4 = 0x30000004,
  PARAMLIST_BITRATEMODE_VBR5 = 0x30000005,
  PARAMLIST_BITRATEMODE_VBR6 = 0x30000006,
  PARAMLIST_BITRATEMODE_VBR0 = 0x30000007,
  PARAMLIST_BITRATEMODE_INVALID = 0x3fffffff
} PARAMLIST_BITRATEMODE;

typedef enum {
  PARAMLIST_SBRSIGNALING_OFF = 0x03000000,
  PARAMLIST_SBRSIGNALING_EXPL_BC = 0x03000001,
  PARAMLIST_SBRSIGNALING_EXPL_HIER = 0x03000002,
  PARAMLIST_SBRSIGNALING_IMPLICIT = 0x03000003,
  PARAMLIST_SBRSIGNALING_INVALID = 0x73ffffff
} PARAMLIST_SBRSIGNALING;

typedef enum {
  PARAMLIST_CONFIGSET_MP4 = 0x00300000,
  PARAMLIST_CONFIGSET_DRM30 = 0x00300001,
  PARAMLIST_CONFIGSET_DRMPLUS = 0x00300002,
  PARAMLIST_CONFIGSET_DASH = 0x00300003,
  PARAMLIST_CONFIGSET_SEEKABLE = 0x00300004,
  PARAMLIST_CONFIGSET_INVALID = 0x7f3fffff
} PARAMLIST_CONFIGSET;

typedef enum {
  PARAMLIST_PRESET_AUDIO_ARCHIVE = 0x003a0000,
  PARAMLIST_PRESET_AUDIO_STREAMING = 0x003a0001,
  PARAMLIST_PRESET_AV_STREAMING = 0x003a0002,
  PARAMLIST_PRESET_LIVE_STREAMING = 0x003a0003,
  PARAMLIST_PRESET_INVALID = 0x7f3fffff
} PARAMLIST_PRESET;

typedef enum {
  PARAMLIST_CONFIGSTATUS_VALID = 0x003b0000,
  PARAMLIST_CONFIGSTATUS_INVALID = 0x003b0001
} PARAMLIST_CONFIGSTATUS;

typedef enum {
  PARAMLIST_RAP_PROPERTY_OFF = 0x002b0000,
  PARAMLIST_RAP_PROPERTY_ACCESS = 0x002b0001,
  PARAMLIST_RAP_PROPERTY_SWITCHABLE = 0x002b0002,
  PARAMLIST_RAP_PROPERTY_SEEKABLE = 0x002b0003,
  PARAMLIST_RAP_PROPERTY_INVALID = 0x7f2affff
} PARAMLIST_RAP_PROPERTY;

typedef enum {
  PARAMLIST_RAP_OCCURRENCE_OFF = 0x002c0000,
  PARAMLIST_RAP_OCCURRENCE_CONSTANT_INTERVAL = 0x002c0001,
  PARAMLIST_RAP_OCCURRENCE_ON_DEMAND = 0x002c0002,
  PARAMLIST_RAP_OCCURRENCE_INVALID = 0x7f2affff
} PARAMLIST_RAP_OCCURRENCE;

typedef enum {
  PARAMLIST_PRIMING_FULL = 0x002d0000,
  PARAMLIST_PRIMING_NONE = 0x002d0001,
  PARAMLIST_PRIMING_STDDELAY = 0x002d0002,
  PARAMLIST_PRIMING_INVALID = 0x7f2dffff
} PARAMLIST_PRIMING;

typedef enum {
  PARAMLIST_FLUSHINGMODE_DEFAULT = 0x002e0000,
  PARAMLIST_FLUSHINGMODE_SYNC = 0x002e0001,
  PARAMLIST_FLUSHINGMODE_INVALID = 0x7f2effff
} PARAMLIST_FLUSHINGMODE;

typedef enum {
  PARAMLIST_PREROLLFRAMES_ON = 0x003a0000,
  PARAMLIST_PREROLLFRAMES_OFF = 0x003a0001,
  PARAMLIST_PREROLLFRAMES_INVALID = 0x7f3affff
} PARAMLIST_PREROLLFRAMES;

typedef enum {
  PARAMLIST_DRCMODE_OFF = 0x003c0000,
  PARAMLIST_DRCMODE_LN_NE_LI_GE_LRACONTROL = 0x003c0003,
  PARAMLIST_DRCMODE_INVALID = 0x7f3cffff
} PARAMLIST_DRCMODE;

typedef enum {
  PARAMLIST_DRCCHARACTERISTIC_DEFAULT = 0x003c0005,
  PARAMLIST_DRCCHARACTERISTIC_EXTERN = 0x003c0006,
  PARAMLIST_DRCCHARACTERISTIC_FILMSTANDARD = 0x003c0007,
  PARAMLIST_DRCCHARACTERISTIC_FILMLIGHT = 0x003c0008,
  PARAMLIST_DRCCHARACTERISTIC_MUSICSTANDARD = 0x003c0009,
  PARAMLIST_DRCCHARACTERISTIC_MUSICLIGHT = 0x003c0010,
  PARAMLIST_DRCCHARACTERISTIC_SPEECH = 0x003c0011,
  PARAMLIST_DRCCHARACTERISTIC_INVALID = 0x003c0012
} PARAMLIST_DRCCHARACTERISTIC;

typedef enum {
  PARAMLIST_LIVE_LRAC_ON = 1,
  PARAMLIST_LIVE_LRAC_OFF = 0,
  PARAMLIST_LIVE_LRAC_INVALID = -1
} PARAMLIST_LIVE_LRAC;

typedef enum {
  PARAMLIST_MPEG4_DRC_LIGHT_PROF_INVALID = -2,
  PARAMLIST_MPEG4_DRC_LIGHT_PROF_NOT_PRESENT = -1,
  PARAMLIST_MPEG4_DRC_LIGHT_PROF_NONE = 0,
  PARAMLIST_MPEG4_DRC_LIGHT_PROF_FILMSTANDARD = 1,
  PARAMLIST_MPEG4_DRC_LIGHT_PROF_FILMLIGHT = 2,
  PARAMLIST_MPEG4_DRC_LIGHT_PROF_MUSICSTANDARD = 3,
  PARAMLIST_MPEG4_DRC_LIGHT_PROF_MUSICLIGHT = 4,
  PARAMLIST_MPEG4_DRC_LIGHT_PROF_SPEECH = 5,
  PARAMLIST_MPEG4_DRC_LIGHT_EXTERNAL_GAIN = 6
} PARAMLIST_MPEG4_DRC_LIGHT_PROF;
typedef enum {
  PARAMLIST_MPEG4_DRC_HEAVY_PROF_INVALID = -2,
  PARAMLIST_MPEG4_DRC_HEAVY_PROF_NOT_PRESENT = -1,
  PARAMLIST_MPEG4_DRC_HEAVY_PROF_NONE = 0,
  PARAMLIST_MPEG4_DRC_HEAVY_PROF_FILMSTANDARD = 1,
  PARAMLIST_MPEG4_DRC_HEAVY_PROF_FILMLIGHT = 2,
  PARAMLIST_MPEG4_DRC_HEAVY_PROF_MUSICSTANDARD = 3,
  PARAMLIST_MPEG4_DRC_HEAVY_PROF_MUSICLIGHT = 4,
  PARAMLIST_MPEG4_DRC_HEAVY_PROF_SPEECH = 5,
  PARAMLIST_MPEG4_DRC_HEAVY_EXTERNAL_GAIN = 6
} PARAMLIST_MPEG4_DRC_HEAVY_PROF;

typedef enum {
  PARAMLIST_MPEG4_METADATA_MODE_INVALID = -1,
  PARAMLIST_MPEG4_METADATA_MODE_NONE = 0,
  PARAMLIST_MPEG4_METADATA_MODE_MPEG = 1,
  PARAMLIST_MPEG4_METADATA_MODE_MPEG_ETSI = 2
} PARAMLIST_MPEG4_METADATA_MODE;

typedef enum {
  PARAMLIST_MPEG4_DMX_GAIN_INVALID = -1,
  PARAMLIST_MPEG4_DMX_GAIN_0_dB = 0,
  PARAMLIST_MPEG4_DMX_GAIN_1_5_dB = 1,
  PARAMLIST_MPEG4_DMX_GAIN_3_dB = 2,
  PARAMLIST_MPEG4_DMX_GAIN_4_5_dB = 3,
  PARAMLIST_MPEG4_DMX_GAIN_6_dB = 4,
  PARAMLIST_MPEG4_DMX_GAIN_7_5_dB = 5,
  PARAMLIST_MPEG4_DMX_GAIN_9_dB = 6,
  PARAMLIST_MPEG4_DMX_GAIN_INF = 7
} PARAMLIST_MPEG4_DMX_GAIN;

typedef enum {
  PARAMLIST_MPEG4_DSUR_INVALID = -1,
  PARAMLIST_MPEG4_DSUR_NOT_INDICATED = 0,
  PARAMLIST_MPEG4_DSUR_NOT_USED = 1,
  PARAMLIST_MPEG4_DSUR_IS_USED = 2
} PARAMLIST_MPEG4_DSUR_IND;

typedef enum {
  PARAMLIST_MPEG4_DRCPRESENTATION_INVALID = -1,
  PARAMLIST_MPEG4_DRCPRESENTATION_NOT_INDICATED = 0,
  PARAMLIST_MPEG4_DRCPRESENTATION_MODE_1 = 1,
  PARAMLIST_MPEG4_DRCPRESENTATION_MODE_2 = 2
} PARAMLIST_MPEG4_DRCPRESENTATION;

typedef enum {
  PARAMLIST_MPEG4_WRITE_PCE_MIXDN_INVALID = -1,
  PARAMLIST_MPEG4_WRITE_PCE_MIXDN_OFF = 0,
  PARAMLIST_MPEG4_WRITE_PCE_MIXDN_ON = 1
} PARAMLIST_MPEG4_WRITE_PCE_MIXDN;

typedef enum {
  PARAMLIST_MPEG4_ETSIDMXPRESENT_INVALID = -1,
  PARAMLIST_MPEG4_ETSIDMXPRESENT_FALSE = 0,
  PARAMLIST_MPEG4_ETSIDMXPRESENT_TRUE = 1
} PARAMLIST_MPEG4_ETSIDMXPRESENT;

typedef enum {
  PARAMLIST_MPEG4_PSEUDO_SUR_INVALID = -1,
  PARAMLIST_MPEG4_PSEUDO_SUR_OFF = 0,
  PARAMLIST_MPEG4_PSEUDO_SUR_ON = 1
} PARAMLIST_MPEG4_PSEUDO_SUR_ENABLE;

typedef enum {
  PARAMLIST_NO_START_STOP_INVALID = -1,
  PARAMLIST_NO_START_STOP_OFF = 0,
  PARAMLIST_NO_START_STOP_ON = 1
} PARAMLIST_NO_START_STOP;

typedef enum {
  PARAMLIST_VALIDATE_CONFIGURATION_OFF = 0,
  PARAMLIST_VALIDATE_CONFIGURATION_ON = 1
} PARAMLIST_VALIDATE_CONFIGURATION;

typedef enum {
  PARAMLIST_PARAMETER_AOT = 0x1000000,
  PARAMLIST_PARAMETER_BITRATE = 0x1000001,
  PARAMLIST_PARAMETER_BITRATEMIN = 0x1000002,
  PARAMLIST_PARAMETER_BITRATEMAX = 0x1000003,
  PARAMLIST_PARAMETER_INSAMPLERATE = 0x1000004,
  PARAMLIST_PARAMETER_CHANNELCONFIG = 0x1000005,
  PARAMLIST_PARAMETER_QUALITY = 0x1000006,
  PARAMLIST_PARAMETER_HBE = 0x1000007,
  PARAMLIST_PARAMETER_SBR = 0x1000008,
  PARAMLIST_PARAMETER_GRANULELENGTH = 0x1000009,
  PARAMLIST_PARAMETER_TRANSPORTFORMAT = 0x1000010,
  PARAMLIST_PARAMETER_COREMODE = 0x1000011,
  PARAMLIST_PARAMETER_SBRSTARTFREQ = 0x1000013,
  PARAMLIST_PARAMETER_SBRSTOPFREQ = 0x1000014,
  PARAMLIST_PARAMETER_SBRRAISEDXOVERFREQ = 0x1000015,
  PARAMLIST_PARAMETER_OUTSAMPLERATE = 0x1000016,
  PARAMLIST_PARAMETER_ACELPMODEINDEX = 0x1000017,
  PARAMLIST_PARAMETER_ACELPFSCALE = 0x1000018,
  PARAMLIST_PARAMETER_SBRRATIO = 0x1000019,
  PARAMLIST_PARAMETER_UNIFIEDSTEREO = 0x1000020,
  PARAMLIST_PARAMETER_SBRPVC = 0x1000022,
  PARAMLIST_PARAMETER_AUDIOBANDWIDTH = 0x1000023,
  PARAMLIST_PARAMETER_LIB_VERSION = 0x1000025,
  PARAMLIST_PARAMETER_LIB_NAME = 0x1000026,
  PARAMLIST_PARAMETER_LIB_BUILDDATE = 0x1000027,
  PARAMLIST_PARAMETER_FRAMESAMPLES = 0x1000028,
  PARAMLIST_PARAMETER_BITRESERVOIRLEVEL = 0x1000029,
  PARAMLIST_PARAMETER_BITRESERVOIRBITS = 0x1000030,
  PARAMLIST_PARAMETER_BITRESERVOIRBITS_MAX = 0x1000031,
  PARAMLIST_PARAMETER_CODECDELAY = 0x1000032,
  PARAMLIST_PARAMETER_BITRATELIMIT = 0x1000034,
  PARAMLIST_PARAMETER_PROFILE_LEVEL = 0x1000035,
  PARAMLIST_PARAMETER_SAMPLES_NEXT = 0x1000036,
  PARAMLIST_PARAMETER_SAMPLES_LEFT = 0x1000037,
  PARAMLIST_PARAMETER_TSD = 0x1000038,
  PARAMLIST_PARAMETER_BITRATEMODE = 0x1000039,
  PARAMLIST_PARAMETER_SBRSIGNALING = 0x1000040,
  PARAMLIST_PARAMETER_ALLOUTSAMPLERATE = 0x1000042,
  PARAMLIST_PARAMETER_TRANSPORTFORMAT_SUBFRAMES = 0x1000044,
  PARAMLIST_PARAMETER_USAC_MAX_IF_DIST = 0x1000045,
  PARAMLIST_PARAMETER_MIN_OUTBUF_SIZE = 0x1000046,
  PARAMLIST_PARAMETER_ANC_BYTES_PER_FRAME = 0x1000047,
  PARAMLIST_PARAMETER_ANC_BITRATE = 0x1000048,
  PARAMLIST_PARAMETER_ANC_BYTES_LEFT = 0x1000049,
  PARAMLIST_PARAMETER_CONFIGSET = 0x1000050,
  PARAMLIST_PARAMETER_NOISEFILLING = 0x1000051,
  PARAMLIST_PARAMETER_TNS = 0x1000052,
  PARAMLIST_PARAMETER_ENHANCED_PULSESEARCH = 0x1000053,
  PARAMLIST_PARAMETER_STEREOCONFIGIDX = 0x1000054,
  PARAMLIST_PARAMETER_PREROLLFRAMES = 0x1000058,
  PARAMLIST_PARAMETER_AUDIOPREROLLOUTOFBITRES = 0x1000059,
  PARAMLIST_PARAMETER_MPEGSNUMPARAMBANDS = 0x1000061,
  PARAMLIST_PARAMETER_MPEGS_HIGHRATE_MODE = 0x1000062,
  PARAMLIST_PARAMETER_SBRFIXBORDERFORINDEPFLAG = 0x1000063,
  PARAMLIST_PARAMETER_LOWDELAYSWITCHING = 0x1000064,
  PARAMLIST_PARAMETER_PRIMING_MODE = 0x1000065,
  PARAMLIST_PARAMETER_RAP_INTERVAL = 0x1000066,
  PARAMLIST_PARAMETER_PRIMING = 0x1000067,
  PARAMLIST_PARAMETER_STANDARDDELAY = 0x1000068,
  PARAMLIST_PARAMETER_LOUDNESS_LEVEL = 0x1000069,
  PARAMLIST_PARAMETER_MIN_INBUF_SIZE = 0x1000071,
  PARAMLIST_PARAMETER_MAXBITRATEPERSEGMENT = 0x1000072,
  PARAMLIST_PARAMETER_STREAMID = 0x1000073,
  PARAMLIST_PARAMETER_SAMPLE_PEAK = 0x1000075,
  PARAMLIST_PARAMETER_ADDITIONAL_SAMPLE_REQUEST = 0x1000076,
  PARAMLIST_PARAMETER_DISABLE_LOUDNESS = 0x1000077,
  PARAMLIST_PARAMETER_FLUSHINGMODE = 0x1000078,
  PARAMLIST_PARAMETER_RAP_MIN_SAMPLES_IN_ADVANCE = 0x1000079,
  PARAMLIST_PARAMETER_RAP_PROPERTY = 0x1000080,
  PARAMLIST_PARAMETER_RAP_OCCURRENCE = 0x1000081,
  PARAMLIST_PARAMETER_DRC_MODE = 0x1000082,
  PARAMLIST_PARAMETER_MPEG4_DRC_LIGHT_PROF = 0x1000089,
  PARAMLIST_PARAMETER_MPEG4_DRC_LIGHT_TARGET_LEVEL = 0x1000090,
  PARAMLIST_PARAMETER_MPEG4_DRC_HEAVY_PROF = 0x1000091,
  PARAMLIST_PARAMETER_MPEG4_DRC_HEAVY_TARGET_LEVEL = 0x1000092,
  PARAMLIST_PARAMETER_ALBUM_LOUDNESS_LEVEL = 0x1000093,
  PARAMLIST_PARAMETER_MPEGD_DRC_TARGET_LOUDNESS_RANGE = 0x1000095,
  PARAMLIST_PARAMETER_RAP_MIN_INTERVAL_SAMPLES = 0x1000099,
  PARAMLIST_PARAMETER_RAP_ON_DEMAND_ADVANCED_MODE = 0x1000100,
  PARAMLIST_PARAMETER_PRESET = 0x1000101,
  PARAMLIST_PARAMETER_MPEG2AAC = 0x1000102,
  PARAMLIST_PARAMETER_RAP_INTERVAL_SAMPLES = 0x1000103,
  PARAMLIST_PARAMETER_USAC_MAX_IF_DIST_SAMPLES = 0x1000104,
  PARAMLIST_PARAMETER_VALIDATE_CONFIGURATION = 0x1000105,
  PARAMLIST_PARAMETER_ANCHOR_LOUDNESS_LEVEL = 0x1000106,
  PARAMLIST_PARAMETER_LOUDNESS_DATA = 0x1000107,
  PARAMLIST_PARAMETER_ALLOW_SHORTEST_RAP_INTERVAL = 0x1000108,
  PARAMLIST_PARAMETER_DISABLE_LOUDNESS_MEASUREMENT = 0x1000109,
  PARAMLIST_PARAMETER_LIVE_LOUDNESS_LEVEL = 0x1000110,
  PARAMLIST_PARAMETER_LIVE_SAMPLE_PEAK = 0x1000111,
  PARAMLIST_PARAMETER_LIVE_MODE = 0x1001112,
  PARAMLIST_PARAMETER_LIVE_LOUDNESS_REL_MAX_GAIN = 0x1001113,
  PARAMLIST_PARAMETER_LIVE_LRAC = 0x1000112,
  PARAMLIST_PARAMETER_CONTINUOUS_BIT_RATES = 0x1000113,
  PARAMLIST_PARAMETER_INTERNAL_LOUDNESS_VERIFICATION = 0x1000114,
  PARAMLIST_PARAMETER_INTERNAL_MEASURED_LOUDNESS = 0x1000115,
  PARAMLIST_PARAMETER_INTERNAL_MEASURED_SAMPLE_PEAK = 0x1000116,
  PARAMLIST_PARAMETER_MPEG4_PROG_REF_LEVEL = 0x1000117,
  PARAMLIST_PARAMETER_MPEG4_CENTER_MIX_LEVEL = 0x1000123,
  PARAMLIST_PARAMETER_MPEG4_SURROUND_MIX_LEVEL = 0x1000124,
  PARAMLIST_PARAMETER_MPEG4_WRITE_PCE_MIXDOWN_IDX = 0x1000125,
  PARAMLIST_PARAMETER_MPEG4_ETSI_DWNMIX_PRESENT = 0x1000126,
  PARAMLIST_PARAMETER_MPEG4_DOLBY_SURROUND_MODE = 0x1000127,
  PARAMLIST_PARAMETER_MPEG4_DRC_PRES_MODE = 0x1000128,
  PARAMLIST_PARAMETER_MPEG4_METADATA_MODE = 0x1000129,
  PARAMLIST_PARAMETER_MPEG4_DRC_EXT_DRC_GAIN = 0x1000130,
  PARAMLIST_PARAMETER_MPEG4_DRC_EXT_COMP_GAIN = 0x1000131,
  PARAMLIST_PARAMETER_MPEG4_PSEUDO_SUR_DMX_ENABLE = 0x1000132,
  PARAMLIST_PARAMETER_MPEG4_NO_START_STOP_SEQUENCE = 0x1000133,
  PARAMLIST_PARAMETER_QUIET_LOUDNESS_THRESHOLD = 0x1000134,
  PARAMLIST_PARAMETER_SAMPLES_MAX = 0x1000135,
  PARAMLIST_PARAMETER_INTERNAL_MEASURED_ANCHOR_LOUDNESS = 0x1000140,

  PARAMLIST_PARAMETER_DEVELOPER = 0x11fffff,
  PARAMLIST_PARAMETER_ADVANCED = 0x12fffff,
  PARAMLIST_PARAMETER_ADVANCED_LIVE_ENCODING = 0x13fffff,
  PARAMLIST_PARAMETER_ADVANCED_DRC_CONTROL = 0x14fffff,
  PARAMLIST_PARAMETER_ADVANCED_LOUDNESS_CONTROL_1 = 0x15fffff,
  PARAMLIST_PARAMETER_ADVANCED_LOUDNESS_CONTROL_2 = 0x16fffff,
  PARAMLIST_PARAMETER_ADVANCED_LEGACY_AAC_SUPPORT = 0x17fffff,
  PARAMLIST_PARAMETER_ADVANCED_RAP_CONTROL = 0x18fffff,
  PARAMLIST_PARAMETER_ADVANCED_RATE_CONTROL = 0x19fffff,
  PARAMLIST_PARAMETER_ADVANCED_BACKWARDS_COMPATIBILITY = 0x20fffff,
  PARAMLIST_PARAMETER_ADVANCED_CONT_BITRATE = 0x21fffff,
  PARAMLIST_PARAMETER_ADVANCED_IF_CONTROL = 0x1Afffff,
  PARAMLIST_PARAMETER_ADVANCED_MESSAGE_CALLBACK = 0X1Bfffff,
  PARAMLIST_PARAMETER_CONFIGSTATUS = 0x1ffffff,
  PARAMLIST_PARAMETER_INVALID = 0x7ffffff
} PARAMLIST_PARAMETER;

typedef enum {
  PARAMLIST_MODE_INVALID = -1,
  PARAMLIST_MODE_APPEND = 0,
  PARAMLIST_MODE_REPLACE = 1,
  PARAMLIST_MODE_APPENDIFMISSING = 2
} PARAMLIST_MODE;

typedef struct paramlist_instance_struct {
  int storedElementsCount;
  char infoModuleVersion[32];
} PARAMLIST_INSTANCE, *PARAMLIST_INSTANCE_HANDLE;

typedef int (*PARAMLIST_CALLBACK_TYPE)(PARAMLIST_INSTANCE_HANDLE const hInstance,
                                       PARAM_INSTANCE_HANDLE const hParam,
                                       void *ptr);

typedef int (*PARAMLIST_CALLBACK_COMPARE)(void *ptr,
                                          PARAMLIST_INSTANCE_HANDLE const hParamList1,
                                          PARAM_INSTANCE_HANDLE const hParam1,
                                          PARAMLIST_INSTANCE_HANDLE const hParamList2,
                                          PARAM_INSTANCE_HANDLE const hParam2);

HANDLE_ERROR_INFO iisParamListNew(
    PARAMLIST_INSTANCE_HANDLE *phInstance);

HANDLE_ERROR_INFO iisParamListDelete(
    PARAMLIST_INSTANCE_HANDLE hInstance);

HANDLE_ERROR_INFO iisParamListAddParam(
    PARAMLIST_INSTANCE_HANDLE const hInstance,
    PARAM_INSTANCE_HANDLE const hParam,
    PARAMLIST_MODE const mode);

HANDLE_ERROR_INFO iisParamListAddParamValue(
    PARAMLIST_INSTANCE_HANDLE const hInstance,
    PARAMLIST_PARAMETER const paramTag,
    PARAM_FORMAT const paramFormat,
    void *pValue,
    PARAMLIST_MODE const mode);

HANDLE_ERROR_INFO iisParamListAddParamArray(
    PARAMLIST_INSTANCE_HANDLE const hInstance,
    PARAMLIST_PARAMETER const paramTag,
    PARAM_FORMAT const paramFormat,
    void *pValue,
    int length,
    PARAMLIST_MODE const mode);

HANDLE_ERROR_INFO iisParamListAddParamValueInt(
    PARAMLIST_INSTANCE_HANDLE const hInstance,
    PARAMLIST_PARAMETER const paramTag,
    int const valueINT,
    PARAMLIST_MODE const mode);

HANDLE_ERROR_INFO iisParamListAddParamValueFloat(
    PARAMLIST_INSTANCE_HANDLE const hInstance,
    PARAMLIST_PARAMETER const paramTag,
    float const valueFLOAT,
    PARAMLIST_MODE const mode);

HANDLE_ERROR_INFO iisParamListAddParamValuePointer(
    PARAMLIST_INSTANCE_HANDLE const hInstance,
    PARAMLIST_PARAMETER const paramTag,
    void *valuePtr,
    PARAMLIST_MODE const mode);

HANDLE_ERROR_INFO iisParamListOverwrite(
    PARAMLIST_INSTANCE_HANDLE *hDest,
    PARAMLIST_INSTANCE_HANDLE const hSrc);

PARAMLIST_INSTANCE_HANDLE iisParamListCopy(
    PARAMLIST_INSTANCE_HANDLE const hInstance);

HANDLE_ERROR_INFO iisParamListPrint(
    PARAMLIST_INSTANCE_HANDLE const hInstance);

HANDLE_ERROR_INFO iisParamListCompare(
    PARAMLIST_INSTANCE_HANDLE const hParamList1,
    PARAMLIST_INSTANCE_HANDLE const hParamList2,
    PARAMLIST_CALLBACK_COMPARE const callbackFunc,
    void *ptr);

HANDLE_ERROR_INFO iisParamListCopyParam(
    PARAMLIST_INSTANCE_HANDLE dest,
    PARAMLIST_INSTANCE_HANDLE const src,
    PARAMLIST_PARAMETER paramTag);

HANDLE_ERROR_INFO iisParamListCopyUnique(
    PARAMLIST_INSTANCE_HANDLE dest,
    PARAMLIST_INSTANCE_HANDLE const src);

HANDLE_ERROR_INFO iisParamListGetParam(
    PARAMLIST_INSTANCE_HANDLE const hInstance,
    int const paramTag,
    PARAM_INSTANCE_HANDLE *phParam);

int iisParamListParamExists(
    PARAMLIST_INSTANCE_HANDLE const hInstance,
    int const paramTag);

HANDLE_ERROR_INFO iisParamListIterate(
    PARAMLIST_INSTANCE_HANDLE const hInstance,
    PARAMLIST_CALLBACK_TYPE const callbackFunc,
    void *ptr);

HANDLE_ERROR_INFO iisParamListStopIterate(
    PARAMLIST_INSTANCE_HANDLE const hInstance);

HANDLE_ERROR_INFO iisParamListRemoveParamTag(
    PARAMLIST_INSTANCE_HANDLE const hInstance,
    int const paramTag);

#ifdef __cplusplus
}
#endif

#endif
